### ISSUE TITLE
"itead" instead of "instead" in menu

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#10]
## Original text
**Switch to servers**
Browse servers `istead`.

## New text
**Switch to servers**
Browse servers `instead`.

## Link to the page this typo was found on
Any dlist.gg page, click on the dropdown menu in the upper right corner. Screenshot:
![Screenshot from 2021-08-27 15-42-04](https://user-images.githubusercontent.com/43812987/131136662-c3d6abee-4bbe-4a22-8d15-2f7aed3638f1.png)
(it's highlighted in red because I ran a spell check on a local copy of the site)

**Comment by audn** [comment]
Fixed 🎉
