### ISSUE TITLE
[bug] adding support invite will cause 500

### ISSUE THREAD

**Issue by Inferno1679** [discordlist-gg/beta-issues#101]
###Description
{
  "id": "791971458372730881",
  "prefix": "! editable",
  "invite": "https://discord.com/oauth2/authorize?client_id=704638190300037200&permissions=8&redirect_url=https://discord.style/thanks&response_type=code&scope=bot%20applications.commands",
  "library": "discord.js",
  "tags": [
    "Logging",
    "Reminders",
    "Memes",
    "Weather",
    "English",
    "Games"
  ],
  "brief_description": "Fun, utility and moderation commands including akinator, tictactoe, embed builder, image changing filters and more!!!\n\n",
  "long_description": "<h1><strong>BotName</strong></h1><p><strong>Describe your bot</strong></p><p>An all around bot! 99.9% uptime If its ever offline we are adding new features! Elysium has over 50 commands with more being added every day! Run the command !help to see all the commands! I add features to it everyday so it gets better and better ! It has music , moderation , fun , and much more! Logs are now here!</p><h3><strong>Commands</strong></h3><hr><ul><li><p><code>!help shows all the commands!</code></p></li></ul><p></p><h3><strong>How to properly setup</strong></h3><hr><p>Just do !help to see all the commands!</p><h3><strong>Links</strong></h3><hr><p><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://discord.gg/jhhJcFtHRC\">Discord</a> <a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"elysiumdevelopment.xyz\">Website </a></p>",
  "features": 69,
  "support_server_url": "https://discord.gg/jhhJcFtHRC",
  "website_url": "https://elysiumdevelopment.xyz",
  "permissions": 2147483647,
  "other_owner_ids": []
}

###Pictures
![image](https://user-images.githubusercontent.com/78994032/137597766-75009871-474a-4db8-98bf-70fa4520bd45.png)

###Browser

Opera GX on Windows 10

**Comment by audn** [comment]
@OhB00 seems like `support_server_url` is causing `other_owner_ids` to fail

**Comment by ChillFish8** [comment]
Invalid now we're on the new backend
