### ISSUE TITLE
[bug] Trying to fetch /v0/users/me/admin-guilds returns 500  

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#103]
### Description
If I go to [/server/new](https://beta.discordlist.gg/server/new) the frontend is trying to fetch https://api.discordlist.gg/v0/users/me/admin-guilds which returns 500 (Internal Server Error) with no response content. 

### Pictures
![image](https://user-images.githubusercontent.com/43812987/137631102-7fe394f4-7e51-4815-aeac-f7a8f7c82838.png)
![image](https://user-images.githubusercontent.com/43812987/137631130-2cf55943-818b-45e7-a2e5-16c4f81d3654.png)

### Browser
Chrome 94 on Linux

**Comment by OhB00** [comment]
Can you send your cookie session cookie to me on discord please bryce#9414

**Comment by OhB00** [comment]
Thanks for that, can you try log in and log out and see if this still happens?

**Comment by OhB00** [comment]
If you want to fix it now visit https://api.discordlist.gg/v0/users/me/revoke then log back in
