### ISSUE TITLE
"recieve" instead of "receive" on pro/premium page

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#11]
## Original text
**Pro badge**
Your personal account including the selected server or bot will `recieve` a badge in the active subscription time.

## New text
Your personal account including the selected server or bot will `receive` a badge in the active subscription time.

## Link to the page this typo was found on
On [https://beta.discordlist.gg/plans](https://beta.discordlist.gg/plans)
Screenshot:
![Screenshot from 2021-08-27 15-46-00](https://user-images.githubusercontent.com/43812987/131137140-55afcbb8-56d2-4cf2-8712-0277372b11d2.png)
(it's highlighted in red because I ran a spell check on a local copy of the site)

**Comment by audn** [comment]
Fixed 🎉
