### ISSUE TITLE
[bug] Disabling Pack in Setting 500 Error

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#116]
### Description
When disabling the `Don't let anyone add Slash Games to packs` setting by clicking the button, it does not and log a 500 Error in the console.

### Pictures
![image](https://user-images.githubusercontent.com/58714825/138617880-3a70265f-a8ad-472c-ad86-d0497c68d79d.png)

### Browser
Brave

### More Information
Payload
```js
{
  "is_packable": false
}
```

**Comment by ChillFish8** [comment]
Invalid with the new backend
