### ISSUE TITLE
you listing

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#12]
## Original text
By upgrading to Pro, **you** listing is likely to get 30% more clicks

## New text
By upgrading to Pro, **your** listing is likely to get 30% more clicks`.`

## Link to the page this typo was found on
https://beta.discordlist.gg/plans
![image](https://user-images.githubusercontent.com/40232557/131160718-1cf2740c-fda3-4a58-8bac-b9217b34946f.png)

**Comment by audn** [comment]
Fixed 🎉
