### ISSUE TITLE
[bug] Failed to fetch pack undefined 

### ISSUE THREAD

**Issue by audn** [discordlist-gg/beta-issues#129]
![image](https://user-images.githubusercontent.com/21041399/163707923-4109d2fd-1486-4c57-ab6d-d16c74572ffe.png)

[[Page it happened on](https://beta.discordlist.gg/user/123057713482694658?open=false)](https://beta.discordlist.gg/user/123057713482694658?open=false)

**Comment by ChillFish8** [comment]
Is this still an issue?
