### ISSUE TITLE
Visiting other user profile pages shows my display name and description after saving changes on my profile page.

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#13]
* Refreshing does fix it for that user page.

## Issue
After saving changes on your user page, visiting another users page shows your display name and description instead of the viewed users.

## Expected Behavior
After setting my display name I expect it to display correctly on my page, and that when I visit other users pages it shows theirs.

## Current Behavior
When I visit other profiles _without_ refreshing it shows _my_ display name instead of the currently viewed user.

## Possible Solution
None to suggest.

## Steps to Reproduce (for bugs)
1. Go to your profile page and edit your display name to something new.
2. Visit any other users profile without refreshing.
3. Look at their display name, it's your newly changed display name instead of theirs.

## Your Environment
* Browser Name: FireFox
* Operating System (desktop or mobile): Windows

![image](https://user-images.githubusercontent.com/14780600/131182180-2dd0c7e3-ed39-44a3-9774-38f7593d4d84.png)

**Comment by OhB00** [comment]
Cache issue? @audn

**Comment by audn** [comment]
when you edit your profile it stores the value in local state (to get instant preview after saving your profile) - I just need to clear the state when router changes

**Comment by audn** [comment]
Fixed 🎉
