### ISSUE TITLE
[bug] Adding bots with tags fails to parse some tags.

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#131]
### Description
Appears that some tags don't work when submitting a bot. (Fails to parse)

### Pictures
![image](https://user-images.githubusercontent.com/14780600/167768691-ec1da6b6-a4b5-4988-8e48-76a8a21acb2e.png)

### Browser
- Firefox v100

**Comment by audn** [comment]
Fixed :tada:
