### ISSUE TITLE
[bug] Scroll disabled after opening side menu. (Mobile)

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#133]
### Description
When opening the side menu and selecting any page besides user settings (they open modals and closing them fixes it) you get stuck and can't scroll anywhere unless you refresh or find another modal to clear it.

### Pictures
![image](https://user-images.githubusercontent.com/14780600/167773192-193c9991-2f40-47b8-92ae-603ccc929be2.png)

### Device
Samsung Galaxy S21

### Browser
- Firefox v100

**Comment by audn** [comment]
Fixed :tada:
