### ISSUE TITLE
[feature] auto-add invite url

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#134]
### Description

auto-add invite url doesnt use the bot's id and uses a redirect_uri for discord.style which will prevent inviting the bot unless the url is whitelisted

**Comment by ChillFish8** [comment]
This should have been removed as it was used for testing @audn

**Comment by audn** [comment]
this field is just for testing

no need to provide a real invite, so just click the auto add for now

**Comment by audn** [comment]
^ it's to save time while adding bots for testing / prefilled value that backend accepts
