### ISSUE TITLE
[bug] "Sign in with Discord" shows JSON response when trying to vote

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#137]
### Steps to reproduce
1. Log out
2. Go to any bot
3. Click on "Voting"
4. Click on "Sign in with Discord"
5. Observe

### Pictures
Buttons to click:
![image](https://user-images.githubusercontent.com/43812987/167877179-e69430d6-51a1-4b47-af87-49d7c27d1625.png)
 
After click:
![image](https://user-images.githubusercontent.com/43812987/167877039-ef8d058a-04d7-4a80-a169-b1f6c889870a.png)

### Browser
Can be reproduced on [Google Chrome Beta (Linux)](https://www.whatismybrowser.com/w/SEFCPJR) and [Google Chrome Mobile (Android 13 Beta)](https://www.whatismybrowser.com/w/2HXZB6J).

**Comment by audn** [comment]
Fixed :tada:
