### ISSUE TITLE
All BotPack categories show 55

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#139]
### Description
The botpack categories show 55, rather than the actual number of bot packs there are for that category.

### Pictures
<img width="1373" alt="Screen Shot 2022-05-12 at 12 15 17 AM" src="https://user-images.githubusercontent.com/55721663/167990918-bca8c700-a04a-4c00-b183-44a8b9ee944e.png">

**Comment by audn** [comment]
This is because the data is hard coded at the moment😁
