### ISSUE TITLE
When "clapping" a user on their profile there is no indication it worked.

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#14]
## Issue
Clapping a user on the profile gives no indication that it succeeded. When you try to clap again you get a `You've already clapped this user.`

## Potential fixes
Have a toastie pop up saying `Clapped that user!` Or some goofy text.
https://www.npmjs.com/package/react-toastify

**Comment by audn** [comment]
Fixed :tada: coming in next push
