### ISSUE TITLE
The "Auto open filters" setting doesn't work as intended

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#141]
### Description
The "Automatically open filters when browser bots" toggle under Dropdown>Website Settings does not work. Whether or not it is enabled, searching bots never opens the filters (tried reloading, searching from home and from search at top-left).

### Browser
 - Safari 15.4

**Comment by audn** [comment]
This is for phones only, as the filter/sort is already shown for dekstop users!

Will rephrase the modal to avoid confusion

**Comment by audn** [comment]
Removed from desktop view! 

It's a setting that changes the phone behaviour.
