### ISSUE TITLE
Consider using "Quick Info" rather than "Expand" on Bot packs

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#142]
### Description
I think it's better to use the same "Quick Info" (or maybe "More Info") button/UI for Bot Packs as is used for bot cards, rather than "Expand". The "Expand" button also doesn't really expand anything, but just replaces fields with completely different info.

### Pictures
<img width="447" alt="Screen Shot 2022-05-12 at 12 22 19 AM" src="https://user-images.githubusercontent.com/55721663/167991634-be4d8556-0696-4109-b945-72cb7df9348a.png">
<img width="463" alt="Screen Shot 2022-05-12 at 12 22 27 AM" src="https://user-images.githubusercontent.com/55721663/167991645-935fbcfa-3b80-43b6-b11e-4cc0d275d058.png">
<img width="466" alt="Screen Shot 2022-05-12 at 12 22 36 AM" src="https://user-images.githubusercontent.com/55721663/167991661-26f4b9d7-9849-4e32-b357-67d721a3c6c6.png">
<img width="461" alt="Screen Shot 2022-05-12 at 12 23 11 AM" src="https://user-images.githubusercontent.com/55721663/167991721-6a4d67f3-1c1b-4c2c-b5f3-69973905b239.png">

**Comment by audn** [comment]
It expands the pack.

On the default view, you can only see the 10(?) first bots in the pack. Clicking "Expand" will show you the entire pack

**Comment by CircuitSacul** [comment]
Makes sense :+1:
