### ISSUE TITLE
Add trending/new/top bots (or servers) to the home page

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#144]
### Description
Right now the main page is a giant banner saying that there's nitro giveaways, and a search box. Would be nice if it also listed some bots/servers as well, such as trending/new/top ones.

**Comment by audn** [comment]
Hi,
We have a new design for the homepage rolling out in the upcoming days.

I will proceed to close the issue.

_Thank you for contributing during beta!_
