### ISSUE TITLE
When a bot has no "unique features", should be "hasn't" not "haven't"

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#145]
## Original text
\<botname> `haven't` added their unique features yet.

## New text
\<botname> `hasn't` added their unique features yet.

## Alternatively
\<botname> doesn't have any unique features listed.

## Link to the page this typo was found on
https://beta.discordlist.gg/bots?category=&tags=, go to Fart bot and click "Quick Info".
<img width="466" alt="Screen Shot 2022-05-12 at 12 48 48 AM" src="https://user-images.githubusercontent.com/55721663/167994143-26a835a0-d2d8-40d9-867c-c253fb52d002.png">

**Comment by ChillFish8** [comment]
Fixed pending next frontend deploy.
