### ISSUE TITLE
Bot icons

### ISSUE THREAD

**Issue by XanderD99** [discordlist-gg/beta-issues#146]
### Description
More a suggestion then a feature. But with add bot / browse bot I would try to find a icon with a robot instead of a man.

### Pictures
![Screenshot_20220512-075717.jpg](https://user-images.githubusercontent.com/36887752/168001977-7e657c3e-93b3-4a30-aa95-2fa4b8459cc6.jpg)

**Comment by audn** [comment]
Good catch!
