### ISSUE TITLE
Small grammar issues on Premium page.

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#15]
## Original text
By upgrading to Pro, `you` listing is likely to get 30% more clicks`.`

## New text
By upgrading to Pro, `your` listing is likely to get 30% more clicks`.`

## Link to the page this typo was found on
https://beta.discordlist.gg/plans
![image](https://user-images.githubusercontent.com/14780600/131183013-c16d7725-5609-4643-b81b-465d82107fb7.png)

**Comment by audn** [comment]
Duplicate of #12
