### ISSUE TITLE
Put the vote button on the bots homepage rather than under a new tab

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#150]
### Description
I personally don't think a vote button warrants it's own page. A simple "Vote" button under "Invite" and "Add to Bot Pack" would be better imo.

I get wanting to have a URL that takes you to the bot's vote page itself, but if I want to vote for a bot I don't think I should have to click 2 times. Maybe you could do both - If you go to the bot page, just click the "Vote" button, but you can still copy a direct "vote link" which takes you to a page with only the vote button.

### Pictures
<img width="1431" alt="Screen Shot 2022-05-12 at 11 45 26 AM" src="https://user-images.githubusercontent.com/55721663/168115609-2ee468cf-c1ed-44c6-a826-d07b3d98447e.png">
<img width="637" alt="Screen Shot 2022-05-12 at 11 46 32 AM" src="https://user-images.githubusercontent.com/55721663/168115833-381c1d5e-5601-4143-bf88-06053a81c0f2.png">

**Comment by audn** [comment]
I agree with you!

Will need some time to tinker my way around this.

**Comment by audn** [comment]
Hi,
I have come to the conclusion that this is a change request that is not worth prioritizing during the beta phase.

Although I agree that the current system is inconvenient, we have a couple of bugs that we should rather prioritize. 

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Comment by audn** [comment]
Hi,
I'm reopening and adding this issue to our internal board.
