### ISSUE TITLE
"Copy vote link" gives link to the non-beta website, resulting in 404

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#151]
### Description
Pretty insignificant, especially considering that this won't be a problem once the site is no longer beta, but thought I'd submit it anyways.

### Pictures
<img width="488" alt="Screen Shot 2022-05-12 at 11 48 37 AM" src="https://user-images.githubusercontent.com/55721663/168116246-45c09caa-0d8d-4059-80b4-af3b00e9e7c7.png">
<img width="451" alt="Screen Shot 2022-05-12 at 11 48 49 AM" src="https://user-images.githubusercontent.com/55721663/168116304-fc5dde8b-458e-411e-a260-91a767f93133.png">
<img width="1440" alt="Screen Shot 2022-05-12 at 11 49 03 AM" src="https://user-images.githubusercontent.com/55721663/168116344-ac8c3d4e-8d1c-4406-9299-d24ead38a0c4.png">

### Browser
 - Safari 15.4

**Comment by ChillFish8** [comment]
Im probably going to mark this as a tech debt ticket, its linking with the correct format, just a diffrent domain. So not too concerned with this.

**Comment by audn** [comment]
It's correct, but "invalid" because we haven't released.

As soon as we release, that link will no longer be invalid.
