### ISSUE TITLE
Maintain the "Show Filters" toggle status when refreshing page

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#152]
### Description
If I search for a bot and my browser window is under a certain size, the filters are hidden by default. I can show the filters by clicking "Show Filters". However, when I click on a bot, then return to where I was (back button) the filters are gone again. Same thing when refreshing the page.

Perhaps just store the toggle status in a cookie.

### Pictures
<img width="1398" alt="Screen Shot 2022-05-12 at 11 56 49 AM" src="https://user-images.githubusercontent.com/55721663/168118004-fcfdfa42-33d9-4196-86cf-600ba6c424ef.png">
<img width="1440" alt="Screen Shot 2022-05-12 at 11 57 02 AM" src="https://user-images.githubusercontent.com/55721663/168118044-59a4d3c6-ee04-4a0b-bb4b-f29e0df82542.png">

**Comment by audn** [comment]
Can add this as a toggle under Website Settings.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/21041399/168493033-bdcfbfa4-6088-4cdd-8cfe-e7613c5d4dfc.png">

**Comment by CircuitSacul** [comment]
Personally I think that this is something that should stay where it is, since filters are going to be used a lot. If anything, just make them always visible, but I wouldn't put it under a modal.

That's just me though

**Comment by audn** [comment]
Hi,
We need to give users on smaller screens the ability to view three bots at once. (x wise)

Hierarchy wise, the filter is less important than bots.

I will proceed to close and mark issue as won't fix. 

_Thank you for contributing during beta!_
