### ISSUE TITLE
Inconsistent bot packs like count

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#154]
### Description
Easiest to watch the video.
https://circuit.is-from.space/Screen_Recording_2022-05-13_at_1.43.48_AM.mov

### Browser
Safari 15.4

**Comment by audn** [comment]
Hi,
Invalid issue.

I will proceed to close the issue.

https://github.com/discordlist-gg/beta-issues/blob/main/CONTRIBUTING.md

_Thank you for contributing during beta!_
