### ISSUE TITLE
Show bot pack like count on "Like" button even if I haven't liked it

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#155]
### Description
Right now the like button for the bot packs has two states:
<img width="96" alt="Screen Shot 2022-05-13 at 1 48 14 AM" src="https://user-images.githubusercontent.com/55721663/168219264-1ea65379-fa9a-49d9-92ae-9ffd8d7d76fa.png">
<img width="106" alt="Screen Shot 2022-05-13 at 1 47 14 AM" src="https://user-images.githubusercontent.com/55721663/168219156-2d3cc2e3-815d-465f-86c9-8a0ff9522736.png">

Imo I should be able to see the like count on this button whether or not I've liked the bot pack.

**Comment by audn** [comment]
Hi,
Considered fixed due to the new pack design we recently announced.

I will proceed to close the issue.

_Thank you for contributing during beta!_
