### ISSUE TITLE
Navbar buttons

### ISSUE THREAD

**Issue by XanderD99** [discordlist-gg/beta-issues#156]
### Description
There is one button to much here in my opinion.

The arrow down button should have your profile picture and you should have to click 2 times to go to your profile. The 2 clicks being clicking on you profile picture, then the dropdown opens with all the options, then you click my profile.

The button that now has your profile picture should just disappear.

extra: I don't know why but it feels like the + is not centered

### Pictures
<img width="173" alt="Screenshot 2022-05-13 at 18 28 08" src="https://user-images.githubusercontent.com/36887752/168327177-6c9d5049-77b0-472d-b44f-bb51479cbc8a.png">

**Comment by ChillFish8** [comment]
Generally speaking, I'm against this idea.

having 3 primary buttons is a fairly standardized layout on navbars especially when they represent 3 fairly distinct groups of operations.

The 3 groups here are:

- Profile 
- Add entity
- Everything else / additional not that important for quick access

The first two are fairly common operations you'd expect to be doing on the site, especially if you're a bot creator where you'll want quick access to your applications. The rest are generally speaking; not used that often in respect to the other items on the nav.
