### ISSUE TITLE
Show "N/A" or "unknown" servers rather than "0"

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#157]
### Description
Right now, if dlist doesn't know the server count of a bot, it shows N/A servers on the bot page but "0 servers" on the bot card (see screenshot). I think it would be better to both be (1) consistent and (2) show "N/A servers", or just not list that stat at all.

### Pictures
<img width="473" alt="Screen Shot 2022-05-13 at 1 26 33 PM" src="https://user-images.githubusercontent.com/55721663/168336374-52e7fbb9-8760-4f73-9ea9-ba8138adc596.png">

**Comment by ChillFish8** [comment]
So we've had this go back and forth quite a bit, and generally speaking from a user's perspective 0 makes more sense than n/a, realistically they're not going to know/care if a bot has or hasn't submitted the info to us.

For consistency purposes i think it's better we stay with 0 being the default if bot owners fail to post info (or discord never release and endpoint)

**Comment by CircuitSacul** [comment]
@ChillFish8 I see what you mean. Maybe just don't list the bot count at all if the bot dev doesn't post stats?

**Comment by ChillFish8** [comment]
I think if we did that it would then make the site look inconsistent with some bots showing it and others not, it's also a slight incentive for bot devs to post their stats rather than just leaving it and letting it not show up.

**Comment by audn** [comment]
Seems to be OK. Closing
