### ISSUE TITLE
Misaligned bullet points for Quick Info

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#158]
### Description
The bullet points for each line under Quick Info is a few pixels higher than the text.

### Pictures
<img width="437" alt="Screen Shot 2022-05-13 at 1 31 10 PM" src="https://user-images.githubusercontent.com/55721663/168337051-ee0be2f0-a22e-47e7-9528-c77fa2f69463.png">

### Browser
Safari 15.4

**Comment by audn** [comment]
Fixed :tada:
