### ISSUE TITLE
Setting a users slug fails on save.

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#16]
## Expected Behavior
When setting a slug for your user profile and saving, expect to refresh the page click edit user and see the existing slug.

## Current Behavior
When setting slug error is thrown in console and the slug obviously does not get set.
![image](https://user-images.githubusercontent.com/14780600/131184468-8605d8b4-2153-497d-b9f5-1f25f0de3eda.png)

## Guessing the issue.
With no codebase knowledge, I'm guessing it fails because I haven't set my slug before and it has to do with empty string or some null previous value.

## Steps to Reproduce (for bugs)
1. Go to your user page
2. Click edit.
3. Change your slug, or add if it's not set.
4. Click save and check console.

## Context
I can't get my super cool omega /panku slug page!!!

## Your Environment
* Browser Name: FireFox
* Operating System (desktop or mobile): Windows

**Comment by OhB00** [comment]
Can you share the network request pl;ease?

**Comment by OhB00** [comment]
@audn, think this happens when a user doesn't have premium?

**Comment by Uhuh** [comment]
@OhB00 yeah, here's there network request.
![image](https://user-images.githubusercontent.com/14780600/131256666-ccc557d4-6f3a-4364-9071-ff3a1218aa9a.png)

**Comment by OhB00** [comment]
Think its fixed?
