### ISSUE TITLE
Unable to sumbit bot without providing invite link

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#160]
### Description
According to the slug of the field, "If left empty, we will automatically generate a link without permissions." However, when I try to submit without providing a link, I get
```
error occurred (better error handling coming soon dw)
"parse request payload error: failed to parse \"DiscordInvite\": invalid invite given (occurred while parsing \"BotSubmission\")"
```

**Comment by ChillFish8** [comment]
I think the plan is to keep this as a required field but probably needs the form adjusted @audn

**Comment by audn** [comment]
Fixed!

Default link if no value is received from the user should be 
```jsx
https://discord.com/oauth2/authorize?client_id=${data.id}&scope=bot&permissions=2147486720
```
