### ISSUE TITLE
Unable to edit bot

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#161]
### Description
When I try to edit my existing bot, the "Save" button remains disabled no matter what I do. I thought I remembered an issue about this but I couldn't find it in the issue tracker.

### Browser
Safari 15.4

**Comment by ChillFish8** [comment]
We need more detail if you can provide it. I.e what fields are populated and with what values?

**Comment by CircuitSacul** [comment]
@ChillFish8 Made a screen recording https://circuit.is-from.space/Screen_Recording_2022-05-14_at_5.23.12_PM.mov

I suspect that this might only be an issue with Safari.

**Comment by ChillFish8** [comment]
hmmm possibly, i cant reproduce this but I know @audn develops on mac so ??

**Comment by CircuitSacul** [comment]
Putting this here for reference https://circuit.is-from.space/Screen_Recording_2022-05-14_at_10.03.33_PM.mov

**Comment by audn** [comment]
Okay so

> Putting this here for reference https://circuit.is-from.space/Screen_Recording_2022-05-14_at_10.03.33_PM.mov

Is this issue only right after you make a bot? So as soon as you refresh the page, it works like it's supposed to?

And for the issue with features.. that's a big rip

**Comment by CircuitSacul** [comment]
@audn yeah that seems to be the case. Though there are times even after I refresh that the Save button fails to show up (e.g. when clearing or unchecking a field)

**Comment by audn** [comment]
Fixed :tada:
