### ISSUE TITLE
Show "Continue" or "Finish" rather than "Save"

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#162]
### Description
When I edit my profile without saving, the next time I go to my profile I see the "Unsaved changes" banner (see screenshot). When you click "Save", it doesn't actually save, it just takes you to where you left off (which makes sense). I suggest changing the wording to reflect that (such as "Continue" or "Finish").

### Pictures
<img width="1437" alt="Screen Shot 2022-05-13 at 5 09 51 PM" src="https://user-images.githubusercontent.com/55721663/168389998-ee5f250e-743d-4e46-8e55-ee2890929e05.png">

**Comment by ChillFish8** [comment]
Changed to `Continue Editing` so that it's more clear to the user.

Pending next deployment.
