### ISSUE TITLE
1 or 3 periods, but not 2

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#164]
## Original text
Oh, well`..`

## New text
Oh, well`...`

## Link to the page this typo was found on
https://beta.discordlist.gg/user/321733774414970882?tab=applications
Under "bots"

<img width="978" alt="Screen Shot 2022-05-13 at 5 14 30 PM" src="https://user-images.githubusercontent.com/55721663/168390462-4f4e8865-9ea5-43d7-afe6-8fc747802a57.png">

**Comment by ChillFish8** [comment]
Corrected to one `.`

Pending next deployment.
