### ISSUE TITLE
Toasts cover navbar links and cannot be dismissed

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#165]
### Description
When a toast appears on the page, it covers some of the links (Bot Packs and Servers) in the navbar, and cannot be dismissed (I have to wait a few seconds). This could be irritating.

### Pictures
<img width="582" alt="Screen Shot 2022-05-13 at 5 19 25 PM" src="https://user-images.githubusercontent.com/55721663/168390964-bfa668fa-2a21-4959-9646-180f66ae9ab6.png">

### Browser
Safari 15.4

**Comment by audn** [comment]
Moved it to `bottom-center`.

Will keep it there for testing until someone makes a new issue saying it's irritating
