### ISSUE TITLE
Clicking link inside bot description appears to open duplicate sites

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#166]
### Description
Here, clicking the beta-issues link opens dlist.gg
https://circuit.is-from.space/Screen_Recording_2022-05-13_at_5.25.51_PM.mov

Here, clicking the amazon link opens amazon twice
https://circuit.is-from.space/Screen_Recording_2022-05-13_at_5.29.26_PM.mov

### Browser
Safari 15.4

**Comment by ChillFish8** [comment]
This is probably fixed via the new editor coming soon:tm: so we'll revisit this issue when that goes live 👌

**Comment by audn** [comment]
...wish i saw the comments before I tried to replicate this

Fixed :tada:
