### ISSUE TITLE
"Share bot" doesn't work

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#168]
### Description
When you click the "Share" button, nothing happens (checked clipboard too).

### Pictures
<img width="564" alt="Screen Shot 2022-05-14 at 11 45 43 AM" src="https://user-images.githubusercontent.com/55721663/168439006-18be7801-c3c1-4a92-9fcd-133c668b2497.png">

### Browser
Safari 15.4

**Comment by audn** [comment]
Function not yet implemented
