### ISSUE TITLE
Cannot click Upload banner on user when editing user profile.

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#17]
## Expected Behavior
When clicking on the banner upload area I expect my file system to open so that I can upload an image(or gif) to use for my profile.

## Current Behavior
Clicking on the button currently does nothing.
![image](https://user-images.githubusercontent.com/14780600/131184788-393d58c5-fb73-48fd-a8b3-93d9cc7d1d57.png)

## Possible Solution
* Heard image server is not setup yet.

## Steps to Reproduce (for bugs)
1. Go to your user profile.
2. Click edit
3. Select Banner
4. Attempt to upload a banner.

## Context
Can't show off my super cool omega chad banners.

## Your Environment
* Browser Name: FireFox
* Operating System (desktop or mobile): Windows

**Comment by audn** [comment]
Fixed 🎉
