### ISSUE TITLE
[bug] Links not clearly distinguishable in lists in bot description

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#170]
### Description
Links (`[linkName](Url)`) inside of lists (`-`) look exactly like normal text, which is not a great user experience as users may not know what they can click and what not. 

Note: This behavior only occurs if the links are placed in lists

### Pictures
Description:
![image](https://user-images.githubusercontent.com/43812987/168485127-a63522ad-500d-4963-9353-455b5167d60f.png)
Markdown:
![image](https://user-images.githubusercontent.com/43812987/168485329-19f5e8d7-b5ad-471f-82c2-c85d7775f362.png)

[Bot with this issue](https://beta.discordlist.gg/bot/235148962103951360)

**Comment by audn** [comment]
Fixed :Tada:
