### ISSUE TITLE
[bug] "You have unsaved changes"-Banner is displayed on other user's profile

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#171]
### How to reproduce
1. Go to your profile and edit your bio or something else
2. Leave the page and navigate to another user
3. Observe

### Description
Expected result: Banner is only shown on your profile
Current result: Banner is shown on every user's profile page. This implies that you have edited the user's profile which can be misleading.

### Pictures
![image](https://user-images.githubusercontent.com/43812987/168485904-603a69c4-78a2-4791-9052-accd7915ff36.png)

**Comment by audn** [comment]
Fixed :tada:
