### ISSUE TITLE
[bug] Trying to add a new bot fills in the data from a previously, already added bot

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#172]
### Steps to reproduce
1. Add a bot to dclist
2. Try adding another bot to dclist
3. Observe

### Description
Expected result: The previously entered data is not automatically filled in, as the previous bot has already been added successfully
Current result: The form gets filled with data about a bot that is already added to dclist

### Pictures

https://user-images.githubusercontent.com/43812987/168486296-70f432e3-08e1-49d9-981e-33b6a603b16a.mp4

*This type of auto-save is a great feature btw*

**Comment by audn** [comment]
can you re-create this now? i think it might have gotten fixed on accident

**Comment by SCDerox** [comment]
Yeah, it's fixed ^^
