### ISSUE TITLE
Typos in privacy policy 

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#174]
## Original texts

1. User profile: Anything you update or upload to your profile such as biography, banner, email `adress` and social media links.
2. If you require additional information, please contact [admin@discordlist.gg](mailto:admin@discordlist.gg). Please put which category from the policy you're `reffering` to in the subject line. (eg. "H. Restricted access - My account got banned")

## New text
1. User profile: Anything you update or upload to your profile such as biography, banner, email `address` and social media links.
2. If you require additional information, please contact [admin@discordlist.gg](mailto:admin@discordlist.gg). Please put which category from the policy you're `referring` to in the subject line. (eg. "H. Restricted access - My account got banned")

## Link to the page this typo was found on
Both on https://beta.discordlist.gg/privacy

1. Under A.1 "Data you provide us"
2. Under "Contact information"

**Comment by ChillFish8** [comment]
Fixed pending next deployment.
