### ISSUE TITLE
Add "Starboard" tag

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#175]
### Description
Since there are sooo many bots out there that have the starboard feature, I think it deserves its own tag.

**Comment by audn** [comment]
What category would this go under?

**Comment by CircuitSacul** [comment]
I'd say "Fun" or "Utility" (but I lean towards fun)

**Comment by audn** [comment]
Hi,
The "Starboard" tag can now be found under the "Fun" category. Good suggestion!

_Thank you for contributing during beta!_
