### ISSUE TITLE
Smooth transition of quick info

### ISSUE THREAD

**Issue by XanderD99** [discordlist-gg/beta-issues#176]
### Description
Edit this transition to look more smooth if possible. More specific don't let the title of the bot and the image fade out but let them move so they don't disappear like in the gif.

### Pictures
![ezgif com-gif-maker](https://user-images.githubusercontent.com/36887752/168768006-180b7dd6-edeb-461f-b56d-6f78dced4a3c.gif)

**Comment by audn** [comment]
Hi,
I have come to the conclusion that this is a change request that is not worth prioritizing during the beta phase.

I will add this to our board as a planned feature, but with lower priority than the current/upcoming bugs.

_Thank you for contributing during beta!_
