### ISSUE TITLE
New bot not empty

### ISSUE THREAD

**Issue by XanderD99** [discordlist-gg/beta-issues#177]
### Description
When going to new bot all fields should be empty and not filled in from a previous bot that has been created. 
You could potentially leave it if the user doesn't create the bot but even then I don't see the usecase of leaving the create page and needing to have the data still filled in. Better would just be having some sort of warning before leaving the page and perhaps there you get the options to either save current state for later or discard it.
 

### Browser
- Google Chrome

**Comment by audn** [comment]
Hi,
Can you confirm this is the same behaviour as seen in #172?

**Comment by XanderD99** [comment]
yes it is the same
