### ISSUE TITLE
Carl-bot is too powerful for dlist

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#182]
### Description
Get a 500 internal error when viewing [carl-bot's page](https://beta.discordlist.gg/bot/235148962103951360)

**Comment by XanderD99** [comment]
same for [dlist](https://beta.discordlist.gg/bot/440172584139620354)

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
