### ISSUE TITLE
[bug] Overflowing text on bot page

### ISSUE THREAD

**Issue by DiscordAnaxes** [discordlist-gg/beta-issues#186]
### Description
The bot page options menu beside the bot name, seems to have overflowing text - varying from page to page.

### Pictures

![image](https://user-images.githubusercontent.com/68460474/169028741-7ef57a24-eb07-4c41-b747-838f105336ac.png)
![image](https://user-images.githubusercontent.com/68460474/169028752-68a2f1e7-3305-4d1c-a5a4-2d230b6fbd7b.png)

### Browser
Firefox v100 on Windows 11

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
