### ISSUE TITLE
Dropdown stays AFTER logging out

### ISSUE THREAD

**Issue by Serakoi** [discordlist-gg/beta-issues#189]
### Description
Dropdown stays when logging out

### Pictures
https://images-ext-1.discordapp.net/external/ulmyz7XkxrH_cCJC97Z7_4mPO9RrBh7pCPAIAV_AR7Q/https/ss1.numachi.org/f1rARvXgO9T0ZlyKtYN7pz.png?width=525&height=585
### Browser
Google Chrome

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
