### ISSUE TITLE
[Bug] Bio Not working 

### ISSUE THREAD

**Issue by PhantomDBD** [discordlist-gg/beta-issues#191]
### Description
Tried to add an bio on my profile but it seemed to not work

### Browser

![Screenshot_20220518-155345](https://user-images.githubusercontent.com/68525534/169043509-c7fdf2ce-ca9a-42c4-a0ff-6e1fb49d87af.png)
![Screenshot_20220518-155336](https://user-images.githubusercontent.com/68525534/169043511-5c888ffb-1636-4fa3-b54a-b30e40d7aaee.png)

**Comment by audn** [comment]
Hi, please provide us with your User ID when you make issues like this, saves us some time :D 

I can see that you have a bio now, which makes me thing this was just a slow-update. 

Please re-open issue if issue persists.
