### ISSUE TITLE
[bug] Packes edit

### ISSUE THREAD

**Issue by e0o** [discordlist-gg/beta-issues#196]
### Description

Packes edit description

### Browser

Google chrome ios 15.4

### Pictures

![2C25D490-B08A-4990-A329-343E2BCF3B26](https://user-images.githubusercontent.com/62356945/169065155-1660a181-6cd8-4b52-afb6-2b720fb76054.jpeg)

**Comment by e0o** [comment]
But when he creates a new unit, he does not say this

### Pic

![19F80383-0D53-4ABE-B27E-D8F64DC78D48](https://user-images.githubusercontent.com/62356945/169066822-7e5862a5-6214-4037-a854-2cdd67bc5b97.jpeg)

**Comment by audn** [comment]
Oh true! I just fixed it.

Thanks!
