### ISSUE TITLE
[design] images in bot markdown are ruining layout (not responsive)

### ISSUE THREAD

**Issue by Luna-devv** [discordlist-gg/beta-issues#198]
### Description
Images in the long description break the responsiveness for the info panel

### Pictures
<img width="366" alt="image" src="https://user-images.githubusercontent.com/21041399/169415098-026198bd-7dd7-4e07-a0c7-fa4e6720bba5.png">

### Browser
iOS/Safari
Win11/Edge
Win11/Chrome
Win11/Firefox
Win11/Brave

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
