### ISSUE TITLE
Trying to look at "My Apps" throws error

### ISSUE THREAD

**Issue by PnsDev** [discordlist-gg/beta-issues#20]
## Expected Behavior
Clicking on my apps with no apps should show you that you have no apps.

## Current Behavior
White page with the text: "Application error: a client-side exception has occurred (developer guidance)."

## Steps to Reproduce (for bugs)
1.Click on my apps with no apps

## Your Environment
IOS Safari

**Comment by audn** [comment]
Fixed 🎉
