### ISSUE TITLE
[design flaw] user owned applications are squashed 

### ISSUE THREAD

**Issue by ErginDapaj** [discordlist-gg/beta-issues#200]
### Description
Nasty looking server count and votes.
Device: Samsung S9

### Pictures
![Screenshot_20220520-012036_Chrome.jpg](https://user-images.githubusercontent.com/39377884/169419740-0f953ae8-6a37-429f-9849-1f7130789537.jpg)
### Browser

Chrome

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
