### ISSUE TITLE
[ui] textarea doesn't show minimum characters required 

### ISSUE THREAD

**Issue by e0o** [discordlist-gg/beta-issues#201]
### Description

I can't save edit

### Browser

Google Chrom ios 15.4

### Video

https://user-images.githubusercontent.com/62356945/169496249-79ff37c9-3eae-430a-bea2-360d8358461c.MOV

**Comment by audn** [comment]
Hi,
I see that we have not quite managed to make you aware that this field has a minimum requirement of 25 characters.

Will move this issue to our internal board and close once we have rolled out a fix!

**Comment by audn** [comment]
We have come to the conclusion of not requiring a description for packs.

I will proceed to close the issue.

_Thank you for contributing during beta!_
