### ISSUE TITLE
[bug] Preview / Edit-Button has a line break

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#203]
### Description
The "Preview" (or "Edit") button in the "Detailed description" field has a line-break mid-word which seems weird considering the fact that there is enough space to fit the whole word.

### Pictures

![image](https://user-images.githubusercontent.com/43812987/169526180-83c7da17-e67f-4ef6-9d9e-d217a955aa02.png)
![image](https://user-images.githubusercontent.com/43812987/169526154-83e22ebc-979c-4ea6-ad0a-e3500328d49f.png)

### Suggested change
![image](https://user-images.githubusercontent.com/43812987/169526406-4627591d-004e-44ee-accb-ad439c9da985.png)
![image](https://user-images.githubusercontent.com/43812987/169526430-9bafa488-dbdb-4d53-b15a-0fe4ef318514.png)

**Comment by audn** [comment]
Hi,
I'm not able to reproduce this issue on my end.

Is this still an issue?

_Thank you for contributing during beta!_

**Comment by SCDerox** [comment]
Seems like it's fixed :+1:
