### ISSUE TITLE
[feature] social links should not auto add utm query params

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#207]
### Description

Currently, `?utm_source=dlistgg&utm_medium=socials_panel` is added to social links without even caring about the current query string.

`https://test.com?a=b` -> `https://test.com?a=b?utm_source=dlistgg&utm_medium=socials_panel`

Ideally, it would just not add the utm string at all, because if desired we can just add it ourselves.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/40232557/169562599-9bec1c9f-dffd-402c-aa27-f81d89f94b7e.png">

**Comment by audn** [comment]
Hi,
I tried googling around to find any negative sides by forcing utm source on external links, without luck.

Do you happen to know any downsides except the current system ignoring if the link already has params on it?

**Comment by Le0Developer** [comment]
Yes, I simply don't care where users come from, but it might give users the impression that I do and track their source.

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
