### ISSUE TITLE
Submit bot with no details

### ISSUE THREAD

**Issue by PnsDev** [discordlist-gg/beta-issues#21]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior
You can't submit a bot with no details. (Or it'll tell you to fill certain details out)

## Current Behavior
It sends you to a 404 page

## Possible Solution
Ask the user for more details if fields are empty

## Steps to Reproduce (for bugs)
1. Submit bot with no details

## Your Environment
* Browser Name: Safari
* Operating System (desktop or mobile): IOS

**Comment by audn** [comment]
Most of the fields are not required during early beta (easier to test)
