### ISSUE TITLE
How to make a bot invisible! (Not Patched)

### ISSUE THREAD

**Issue by ErginDapaj** [discordlist-gg/beta-issues#211]
### Page

https://beta.discordlist.gg/bot/411916947773587456

### Description

First, you edit the bot the normal URL would be v0/bots/ID but you change that to v0/users/me 
Then you save the changes, and the changes will go through but then it will hit you with a 404 on the frontend side.
Now that you did all that go back to the bot page edit it and let the changes pass normally, that will make the bot page crash

### Website data

```JSON
Server Error + No Data To Collect
```

**Comment by ErginDapaj** [comment]
A quick fix would be to not allow any data to go through users/me besides the bio, slug, and username!

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
