### ISSUE TITLE
[ui] Report modal can't be scrolled

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#212]
### Page

Any Bot page work the same

### Description

Scrolling on the report modal, does not scroll up. Trying to reach other selection, but scrolling up, just make the modal disappear. 

**Device Used:** Appears on iPhone

### What browsers are you seeing the problem on?

Chrome

**Comment by audn** [comment]
Hi,
I'm not able to reproduce this issue on my end.

Can you confirm that this issue still exist?

**Comment by GamerCreator1** [comment]
This issue no longer exist. 
I will close this issue.
