### ISSUE TITLE
[bug] Not clicking submit on report duplicate say Success

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#213]
### Page

https://beta.discordlist.gg/bot/new

### Description

Typing the same bot id will bring up the duplicate report page, clicking on the report button and then exiting will show the success modal

![image](https://user-images.githubusercontent.com/58714825/169695053-6bcfb26c-c478-4c85-be3f-eb94eb2e2c00.png)

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
