### ISSUE TITLE
[ui] Phone have a extra submit button 

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#214]
### Page

https://beta.discordlist.gg/bot/new

### Description

Comparing Phone Version to the computer version, a extra submit button can been seen
IPhone
![image](https://user-images.githubusercontent.com/58714825/169695386-b0ed4408-a501-478d-af8c-cb05a0fa9e3a.png)

Computer
![image](https://user-images.githubusercontent.com/58714825/169695393-044f79f2-37e4-45ba-9274-4718d8294495.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by SCDerox** [comment]
Same issue with "Save to pack" modals
![image](https://user-images.githubusercontent.com/43812987/169703483-48e99589-e57f-49b0-9b1d-3ddd8c8da115.png)
