### ISSUE TITLE
[ui] Code Style Text not wrapping

### ISSUE THREAD

**Issue by Legit4K** [discordlist-gg/beta-issues#217]
### Page

https://dlist.gg/bot/440172584139620354

### Description

Using `code element markdown` in bot descriptions doesn't seem to wrap properly making the mobile viewing experience sub-optimal. 

### What browsers are you seeing the problem on?

Chrome

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
