### ISSUE TITLE
[bug] Save and close is disabled even after changing the options

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#219]
### Page
https://beta.discordlist.gg/pack/6895987960146508081

### Description

Changing a option type, does not allow you to save the changes
Before
<img width="543" alt="image" src="https://user-images.githubusercontent.com/58714825/169729391-a6666c63-d9c9-42f7-9153-97b691e6a82f.png">
After
<img width="539" alt="image" src="https://user-images.githubusercontent.com/58714825/169729417-c66b2786-6307-4ca5-a7e0-7f8d12d592ff.png">

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
