### ISSUE TITLE
long server name makes the `Add` button disappear

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#22]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior

Server name should be truncated so that the `Add` button remains visible.

## Current Behavior

Server name is clipped at the end of its box but the `Add` button is gone. (you can still click the box!)

## Possible Solution

Truncate server name.

## Steps to Reproduce (for bugs)

1. Name a server `WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW`
2. Go to https://beta.discordlist.gg/server/new
3. Observe the `Add` button disappearing

![Image](https://cdn.discordapp.com/attachments/736932833863663646/881091490430996500/unknown.png)

## Context

Long names are common.

## Your Environment

* Browser Name:
* Operating System (desktop or mobile):

**Comment by audn** [comment]
Fixed 🎉
