### ISSUE TITLE
Botpack filtering doesn't work

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#224]
### Page

https://beta.discordlist.gg/packs?sort=trending&category=

### Description

Filtering by category of bot packs has no effect.

https://files.circuitsacul.dev/Screen_Recording_2022-05-23_at_10.18.51_PM.mov

(sorry for the file link I couldn't get a video to upload directly)

### Notify on issue updates

- [X] Yes

**Comment by CircuitSacul** [comment]
Same goes for bots, it seems.

**Comment by ChillFish8** [comment]
I believe this has already been fixed? This was a UI thing because it didn't send any requests for selected categories.

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
