### ISSUE TITLE
[bug] Close button on setting modal does not close

### ISSUE THREAD

**Issue by Mr-KayJayDee** [discordlist-gg/beta-issues#225]
### Page

Every pages

### Description

The button to close the setting modal does not close the modal.

The modal can be closed by clicking outside of the modal

![Screenshot 2022-05-24 at 09 54 55](https://user-images.githubusercontent.com/46600662/169979185-688db9b5-dac9-4474-8662-c66eb8aee6e0.png)

![Screenshot 2022-05-24 at 09 55 16](https://user-images.githubusercontent.com/46600662/169979252-7380d1d5-f7bf-4b08-b6cf-2a1372d6ac25.png)

### Notify on issue updates

- [X] Yes

### Discord username

Mr¤KayJayDee#8961

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
