### ISSUE TITLE
[ui] Error page 500 double navbar issue

### ISSUE THREAD

**Issue by kikorp78** [discordlist-gg/beta-issues#226]
### Page

https://beta.discordlist.gg/help/article/bots (but can be reproduced on any page)

### Description

![Screenshot_20220524-110619_Chrome](https://user-images.githubusercontent.com/26502356/169995359-fa04defe-d229-4b76-b6f0-3b5bd18ba155.jpg)
![Screenshot_20220524-110627_Chrome](https://user-images.githubusercontent.com/26502356/169995365-5b56a431-6b31-4e35-91eb-3e1ba1cd48cc.jpg)

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [x] Yes

### Discord username

kikorp78#0001

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
