### ISSUE TITLE
[bug/ui] internal on editing bot socials url

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#227]
### Page

https://beta.discordlist.gg/bot/:id/dashboard/edit

### Description

Type anything and then remove it again to get internal error.

https://user-images.githubusercontent.com/40232557/170040030-32c52234-c04f-4e97-beb1-3d9891e2a809.mov

Also this probably be called "Client Error" instead of "Server error"?

### Notify on issue updates

- [X] Yes

### Discord username

leo..#1337

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
