### ISSUE TITLE
[ui] social links are forced to be in a new tab

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#228]
### Page

https://beta.discordlist.gg/bot/823533449717481492/dashboard/edit

### Description

The decision of whether a link should be opened in a new tab or not, should be left to the user and not forced by the website.
(cmd + left click on mac, ctlr + left click for opening in a new tab)

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

leo..#1337

**Comment by Le0Developer** [comment]
Also this: https://medium.com/sedeo/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

**Comment by audn** [comment]
Hi,
I don't see a problem forcing `_blank` on external urs. 

Letting the user decide will cause inconsistency and confuse the user.

Also noticed that we're not returning the proper `<Link>` component in markdowns. This is now fixed.

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
