### ISSUE TITLE
[bug] Internal Server Error bot pack

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#231]
### Page

https://beta.discordlist.gg/bot/727631247198650422

### Description

when adding a bot to a bot pack -> and not logged in will show this when you reach the 5 character mark on the modal

<img width="534" alt="image" src="https://user-images.githubusercontent.com/58714825/170122902-37548b07-f794-47db-ba54-eb8a6874531a.png">

### Notify on issue updates

- [X] Yes

### Discord username

GamerCreator1#1466

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
