### ISSUE TITLE
[bug] Bio change bug

### ISSUE THREAD

**Issue by ghostsnip3rr** [discordlist-gg/beta-issues#232]
### Page

https://beta.discordlist.gg/user/510426136854003713

### Description

When you try to change your bio and exceed 3/4 chars you get Internal Server Error.

### Notify on issue updates

- [X] Yes

### Discord username

ghostsniper#0602

**Comment by ghostsnip3rr** [comment]
Same thing on "Display name"

**Comment by audn** [comment]
Can't recreate.

Made a thread in the beta channel on Discord

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
