### ISSUE TITLE
[bug] "Internal Server Errors" when typing on the bot edit page

### ISSUE THREAD

**Issue by PikaDude** [discordlist-gg/beta-issues#235]
### Page

https://beta.discordlist.gg/bot/:id/dashboard/edit

### Description

https://user-images.githubusercontent.com/18642415/170297870-63f1ecec-4d93-4df2-a570-ef6bcbbdcfb1.mp4

### Notify on issue updates

- [X] Yes

### Discord username

PikaDude#0001

**Comment by PikaDude** [comment]
I can't even type more than a few chars on some fields without this happening, such as the support server invite

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
