### ISSUE TITLE
[bug] Search by default excludes all bots that have at least 1 feature

### ISSUE THREAD

**Issue by PikaDude** [discordlist-gg/beta-issues#236]
### Description

Searching anything by default will search for all bots with 0 "Features".
For example, Erisly has "Interactive Buttons" and "Documentation", so she does not appear in search by default.
Selecting either "Interactive Buttons" or "Documentation" will make her appear in search.

### Notify on issue updates

- [X] Yes

### Discord username

PikaDude#0001

**Comment by audn** [comment]
Not a real issue. Was confused because not all results were showing.

I will proceed to close the issue.

_Thank you for contributing during beta!_
