### ISSUE TITLE
[ui] webhook error message does not disappear after successful update

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#237]
### Page

https://beta.discordlist.gg/bot/:id/dashboard/webhooks

### Description

When updating the webhook and it results in an error, the error is displayed.
After fixing the issue and successfully updating the webhook, the error is not removed.

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

leo..#1337

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
