### ISSUE TITLE
[bug] Incorrectly filtering discord support server invite links to not allow links from discord.com

### ISSUE THREAD

**Issue by EggsLeggs** [discordlist-gg/beta-issues#238]
### Page

https://beta.discordlist.gg/bot/new

### Description

Problem:
The support server invite only accepts https://discord.gg/INVITE but invite links can also be formatted as https://discord.com/invite/INVITE. 
Expected:
The usage of the discord.com links should be allowed.

Example:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/36281195/170357850-f3045aa7-367f-4b1c-8d30-173855b0ce9b.png">

### Notify on issue updates

- [X] Yes

### Discord username

EggsLeggs#0001

**Comment by ChillFish8** [comment]
This should be fixed now. Please retry :)

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
