### ISSUE TITLE
[bug] Description does not clear | Packs

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#239]
### Page

https://beta.discordlist.gg/bot/875371904792424499

### Description

![image](https://user-images.githubusercontent.com/58714825/170502238-9351bf90-d1a3-453d-a2b6-7b3753d309c1.png)

This stay the same in description field and the tags fields.

### Notify on issue updates

- [X] Yes

### Discord username

GamerCreator1#1466

**Comment by audn** [comment]
HI,
What do you mean it doesn't clear?

Are you typing something, then unable to remove it? 
Need more context

**Comment by GamerCreator1** [comment]
Make a new pack -> add the description pack 1 and create it
make another pack => the description will still be pack 1 not a empty field

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
