### ISSUE TITLE
[bug] Bot pack modal delete button don't work

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#244]
### Page

https://beta.discordlist.gg/bot/710566056468676718/vote

### Description

You can't delete a bot with the delete button, it will just add the bot if possible

### Notify on issue updates

- [X] Yes

### Discord username

GamerCreator1#1466

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
