### ISSUE TITLE
[ui] empty pack are showing 

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#246]
### Page

https://beta.discordlist.gg/

### Description

Bot pack list show empty bot pack

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

GamerCreator1#1466

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
