### ISSUE TITLE
[ui] bot pack with no bots shows incorrect message

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#251]
### Page

https://beta.discordlist.gg/pack/890782939936526498

### Description

![image](https://user-images.githubusercontent.com/40232557/170867250-023d5fc1-6e10-4b06-9e78-a26eeae14385.png)

Filters?

### Notify on issue updates

- [X] Yes

### Discord username

leo..#1337

**Comment by audn** [comment]
Hi,
I have come to the conclusion that this is a change request that is not worth prioritizing during the beta phase.

Although I agree that the current system is inconvenient, we have a couple of bugs that we should rather prioritize. 

I will proceed to close the issue.

_Thank you for contributing during beta!_
