### ISSUE TITLE
[ui] impossible to change website settings without logging in

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#253]
### Page

https://beta.discordlist.gg

### Description

Just a terrible design decision imo

### Notify on issue updates

- [X] Yes

### Discord username

leo..#1337

**Comment by audn** [comment]
Hi,
I have come to the conclusion that this is a change request that is not worth prioritizing during the beta phase.

I will proceed to close the issue.

_Thank you for contributing during beta!_
