### ISSUE TITLE
[ui] clear filters does not work with selected tags

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#255]
### Page

https://beta.discordlist.gg/bots?sort=trending&features=0&category=moderation&tags=profanity-filter

### Description

Go to the page, click "reset filters".

### Notify on issue updates

- [X] Yes

### Discord username

leo..#1337

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
