### ISSUE TITLE
[bug] Internal server error while adding bot

### ISSUE THREAD

**Issue by chickenmatty** [discordlist-gg/beta-issues#258]
### Page

https://discordlist.gg/bot/new

### Description

I tried to add my bot, filled in every field and clicked on preview, then got an internal server error

![immagine](https://user-images.githubusercontent.com/44543605/171453647-51bed740-34ce-4bde-8214-adec8e560e06.png)

### Notify on issue updates

- [X] Yes

### Discord username

chickenmatty#4766

**Comment by chickenmatty** [comment]
The bot apparently got added, if you try to visit its page you get an internal server error
https://discordlist.gg/bot/609087387695316992

**Comment by audn** [comment]
Hi,
This issue should be fixed now, please try agian.

**Comment by chickenmatty** [comment]
I got another error (seems related) trying to edit the bot page, should I open another issue?
![screenshot](https://user-images.githubusercontent.com/44543605/171470350-f6d8ee10-4647-4556-81f1-d2b207c09a7e.png)

**Comment by audn** [comment]
Hi,
Can you please test this again now?

**Comment by chickenmatty** [comment]
It seems to be ok, I tried to edit the bot and the page works just fine, haven't had the occasion to see the changes live but it looks ok.
However I found another similar issue while trying to visit MEE6's page😅
https://discordlist.gg/bot/159985870458322944
![screenshot](https://user-images.githubusercontent.com/44543605/171489116-8177cbae-e6c6-453c-99cc-4cc1f4e5e4cb.png)

**Comment by audn** [comment]
#
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
