### ISSUE TITLE
Availability to manipulate embed string through /v0/users/me 

### ISSUE THREAD

**Issue by suffocated** [discordlist-gg/beta-issues#26]
## Expected Behavior

You shouldn't be able to create your own hyperlink through the /v0/users/me endpoint with the display_name key.

## Current Behavior

You're able to manipulate the user information embed through the /v0/users/me endpoint with the display_name key, making so that you can create hyperlinks, whitespace, making your name bold or creating code brackets.

## Possible Solution
Removing illegal characters such as [, ], * etc etc, and making so that only available strings are a-z, 0-9

## Steps to Reproduce (for bugs)

1. Make a post request to /v0/users/me endpoint with the data_raw set to 
``{"bio":"Hello", "display_name":"**[Caasi](https://www.youtube.com/)**\n```Yo```\n<a:dancecat:739893323300339881>"}``

Result would be,

![image](https://user-images.githubusercontent.com/47527704/131220923-734ef063-d243-45a9-a81c-caf47664fba1.png)

**Comment by suffocated** [comment]
Update, also works on /bot endpoint with the 'brief_description' key, as well that you could make a random discord lib as a name, example, your mom.

![image](https://user-images.githubusercontent.com/47527704/131222376-78360bfd-f9d3-4cab-830e-f81fa848fe9c.png)

**Comment by OhB00** [comment]
Works for basically all fields will investigate

**Comment by OhB00** [comment]
Good find, do mentions work?

**Comment by suffocated** [comment]
Hm, you can mention users within the embed itself, but that doesn't ping the user. Though maybe you could use an f-string to send an additional message?

**Comment by OhB00** [comment]
Fixed in https://github.com/discordlist-gg/web-back/commit/16a842d5da4affc11114f359b6e8842d32f478f0

**Comment by OhB00** [comment]
Missed a couple fields https://github.com/discordlist-gg/web-back/commit/679c186a66a389b5739279ee16cd7a2f7ce629a5

**Comment by suffocated** [comment]
same goes for \n

**Comment by OhB00** [comment]
Need a second opinion on this @audn, worth fixing?

**Comment by suffocated** [comment]
Also works with slugs, ```__x__``` results in ```x``` in the embed

**Comment by suffocated** [comment]
In addition, slugs can have invalid symbols such as ```$```

**Comment by audn** [comment]
100% an issue someone else will report, so to avoid duplicates, I'd fix it @OhB00 (low priority though)

**Comment by suffocated** [comment]
In addition, there is an availability to use the site to make zero width names and empty slugs further causing the hyperlink on the embed to be nonfunctional, which in my opinion is pretty severe.
