### ISSUE TITLE
[ui] Profile info doesn’t update immediately 

### ISSUE THREAD

**Issue by doinkythederp** [discordlist-gg/beta-issues#260]
### Page

https://discordlist.gg/user/:id

### Description

After changing my bio, the website takes a couple reloads before I can see the new profile info. It would be nice if I didn’t even have to reload the see the new info, and changing the bio would immediately change what you see.

https://user-images.githubusercontent.com/75394401/171458807-33c532e8-2c5b-4142-861c-91802329f42a.MOV

### What browsers are you seeing the problem on?

Safari (but the issue likely isn’t browser-related)

### Notify on issue updates

- [x] Yes

### Discord username

doinkythederp#6523

**Comment by audn** [comment]
Hi,
This is because of cache.

No way of instantly fixing it I'm afraid.
We are investigating the matter and will try to get it resolved as fast as we can though.

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Comment by doinkythederp** [comment]
> Hi, This is because of cache.
> 
> No way of instantly fixing it I'm afraid. We are investigating the matter and will try to get it resolved as fast as we can though.
> 
> I will proceed to close the issue.
> 
> _Thank you for contributing during beta!_

@audn I think you're misunderstanding what I'm suggesting - I'd like it to work like this:

1. User updates data
2. dlist.gg temporarily overrides data until reload
3. Reloads work like normal
