### ISSUE TITLE
[feature] Replace "Tweet about this" with "Report on GitHub"

### ISSUE THREAD

**Issue by Snazzah** [discordlist-gg/beta-issues#262]
### Description

Tweeting about bugs is a bit weird, you can use a prefilled GitHub issue URL:

`https://github.com/discordlist-gg/beta-issues/issues/new?assignees=&labels=bug&template=bug.yaml&title=%5Bbug%5D+&description=`**`DESCRIPTION`**`&page=`**`https%3A%2F%2Fdiscordlist.gg%2F`**

You can prefill the `description` param with a stacktrace if you want, prefill `page` with the current page URL and even prefill the `discordname` if the user is logged in the page.

### Notify on issue updates

- [X] Yes

### Discord username

Snazzah#0371

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
