### ISSUE TITLE
[ui] Cannot view text below bot description length counter

### ISSUE THREAD

**Issue by doinkythederp** [discordlist-gg/beta-issues#267]
### Page

https://discordlist.gg/bot/new

### Description

I can't tell what I'm writing below the character counter for the description on the New Bot page. The counter should probably move out of the way of the cursor, or at least be partially transparent.

![Screenshot 2022-06-01 12 09 14 PM](https://user-images.githubusercontent.com/75394401/171483336-a21d8361-0718-4bd4-953f-0d2252bfc38d.png)

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Comment by doinkythederp** [comment]
@audn The text counter still covers up text:
![image](https://user-images.githubusercontent.com/75394401/171966585-1a998bcf-5b0c-48b4-b10f-ca64dfe937ac.png)

**Comment by audn** [comment]
Hi,
If you hover over, it will go away!
