### ISSUE TITLE
Add edit button for bots on mobile

### ISSUE THREAD

**Issue by link-discord** [discordlist-gg/beta-issues#269]
### Description

![Screenshot_20220601-223032_Brave](https://user-images.githubusercontent.com/50463727/171499865-8a0ca811-5f98-4964-aa7a-d8e302ca6a8a.jpg)

There is no edit action and therefore no way to edit ur bot on the mobile layout

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

Link#0069

**Comment by link-discord** [comment]
Is this fixed yet

**Comment by audn** [comment]
Hi,
No. I've been on vacation so I haven't had time to work on dlist.

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
