### ISSUE TITLE
[bug] Roles does not appear on profile page

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#27]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior
The profile page show the user roles.

## Current Behavior
Roles does not appear on profile pages.

## Steps to Reproduce (for bugs)
https://beta.discordlist.gg/user/audnwashere

## Your Environment

* Browser Name: Brave
* Operating System (desktop or mobile): Desktop (MacOS)

![image](https://user-images.githubusercontent.com/58714825/131221003-17f27e30-281a-48fa-bcf9-cfe908239430.png)

**Comment by audn** [comment]
Fixed 🎉
