### ISSUE TITLE
[bug] Detailed description requires 301 characters as supposed to 300

### ISSUE THREAD

**Issue by Kyzegs** [discordlist-gg/beta-issues#270]
### Page

https://discordlist.gg/bot/new

### Description

The detailed description when adding a new bot requires 301 characters as supposed to 300

### Notify on issue updates

- [ ] Yes

### Discord username

Kyzegs#7955

**Comment by audn** [comment]
Hi,
I'm afraid I don't understand the issue.

Brief description has a minimum of 25 and max of 250. (We allow you to type 300, but you can't actually save. It's just so that you don't get blocked while typing.)

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Comment by Kyzegs** [comment]
I was referring to the **detailed description**. It does not allow you to save with the given minimum of 300 characters. It only allows you to save once you put in 301 characters.

300 characters (Unable to save):
![false](https://user-images.githubusercontent.com/45851377/172021912-26a48b72-ef60-4b07-9443-3a6f87f73cac.png)

301 characters (Able to save):
![true](https://user-images.githubusercontent.com/45851377/172021909-93462af7-9f19-4dc1-b448-74027008fe44.png)

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
