### ISSUE TITLE
[bug] Can’t create/delete bot packs

### ISSUE THREAD

**Issue by doinkythederp** [discordlist-gg/beta-issues#271]
### Page

https://discordlist.gg/bot/:id

### Description

Creating a bot pack fails and displays an error message.

https://user-images.githubusercontent.com/75394401/171512345-c1b0c1ce-dbf9-4c2d-851a-7edb142b9ec7.MOV

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by doinkythederp** [comment]
Doesn't look like it's an issue anymore

**Comment by audn** [comment]
Hi,
What do you mean still gives errors? I've never heard of that error. 

Can you elaborate? 
Please give steps to re-create

**Comment by doinkythederp** [comment]
Here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/75394401/172017768-4425b78d-f8ba-47b2-a58c-4dfd0b4f2e77.jpeg)
I got this by going to My Apps -> Packs -> [the pack] -> Three dots menu -> Delete pack.

**Comment by audn** [comment]
Hi,
Can you confirm that this is still an issue?

**Comment by doinkythederp** [comment]
I no longer get this exact error, but when deleting a bot pack from My Apps -> Packs I get this one instead: 
![F44B5A81-40F7-4CDC-9342-7D42AFC60C48](https://user-images.githubusercontent.com/75394401/175476344-37ca405a-6430-4120-903b-602ef34e9636.jpeg)
The pack is still successfully deleted - this looks like it’s only UI.

**Comment by audn** [comment]
Hi,
Sorry the extremely late answer. 

This should have gotten fixed last time we spoke, would you mind trying now?

**Comment by lewisfm** [comment]
https://user-images.githubusercontent.com/75394401/197443643-56d1d803-8054-43dc-afed-9f811a533801.mov

Clicking "Delete pack" doesn't appear to do anything anymore @audn

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
