### ISSUE TITLE
[ui] Error messages appear below menus

### ISSUE THREAD

**Issue by doinkythederp** [discordlist-gg/beta-issues#272]
### Description

Error messages are obscured by modal menus, making them hard to notice.

Example: #271 

### What browsers are you seeing the problem on?

Safari

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by audn** [comment]
Hi,
This isn't possible to fix due to how the react-modal package we use works.

Will be fixed in a later version where we eventually remove the current modal system.
