### ISSUE TITLE
Giveaway tag

### ISSUE THREAD

**Issue by thewilloftheshadow** [discordlist-gg/beta-issues#274]
### Description

Could we have a Giveaway tag for giveaway based bots?

### Notify on issue updates

- [X] Yes

### Discord username

TheShadow#8124

**Comment by audn** [comment]
Hi,
What category would you place this new tag under?

**Comment by Luke-6723** [comment]
I would suggest the social category

**Comment by thewilloftheshadow** [comment]
I would put it under fun or utility

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_

<img width="248" alt="image" src="https://user-images.githubusercontent.com/21041399/171991105-4c73da8b-addb-4c2a-b42a-3eba52645698.png">
