### ISSUE TITLE
[feature] Ability to update the name of a bot

### ISSUE THREAD

**Issue by doinkythederp** [discordlist-gg/beta-issues#275]
### Description

After creating a bot, you can't change its name on dlist.gg without deleting the page and remaking it. I'm suggesting a button on the Edit page that updates the bot's name to what it currently is.

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by audn** [comment]
Hi,
Your bot name is fetched from Discord.

If you ever change your name from the developer portal, simply editing the bot on our website is enough for it to update with the newly created name.

I will proceed to close the issue.

_Thank you for contributing during beta!_
