### ISSUE TITLE
[suggestion] Clickable links in bio

### ISSUE THREAD

**Issue by srnyx** [discordlist-gg/beta-issues#276]
### Description

Make links into hyperlinks in user bios.
Not sure if it does this already on computer, but it doesn’t on mobile.

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

srnyx#0001

**Comment by audn** [comment]
Hi,
I have come to the conclusion that this is a change request that is not worth prioritizing during the beta phase.

I will proceed to close the issue.

_Thank you for contributing during beta!_
