### ISSUE TITLE
[bug] cards un-reactive for a while after fetching new page

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#278]
### Description

Quick Info Lag:
https://files.circuitsacul.dev/qi-lag-long.mov
https://files.circuitsacul.dev/qi-lag-short.mov

Normal Quick Info:
https://files.circuitsacul.dev/normal-qi.mov

Additional lag (weird hover behavior):
https://files.circuitsacul.dev/hover-lag.mov

### What browsers are you seeing the problem on?

Safari

### Notify on issue updates

- [X] Yes

### Discord username

CircuitSacul#3397

**Comment by CircuitSacul** [comment]
@audn the new title represents the second issue, but the original title is also an issue. If there are lots of cards, clicking the "Quick Info" button takes around 1 second to work.

**Comment by audn** [comment]
Hi!
Yes! It's the same fault for both of the issues! Fixing one will fix the other😄

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Comment by audn** [comment]
Hi, 
Is this still an issue? @CircuitSacul
