### ISSUE TITLE
Error Messages Not Going Away

### ISSUE THREAD

**Issue by ErginDapaj** [discordlist-gg/beta-issues#279]
### Page

Any Page That Throws Errors

### Description

I figured out when you press an error message that is supposed to go away in 2 seconds it never goes away until you refresh.
It would be a good idea that when you press the error message it vanishes
![Screenshot_20220602-183316_Chrome](https://user-images.githubusercontent.com/39377884/171680288-d79c1fb5-25f3-4022-8032-c8cdec9e9a6e.jpg)

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

Grainger

**Comment by audn** [comment]
Hi,
I think the current behavior is wanted as it gives people who reads slowly the chance to catch up.

However, it shouldn't stay forever.

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
