### ISSUE TITLE
[bug] Unable to clear your display name

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#28]
## Description
Your display name does not clear if you leave it empty.

## Possible Solution
None to suggest

## Steps to Reproduce (for bugs)
1. Go to your profile
2. Edit your display name to have one
3. Delete your display name
4. Save and observe result

**Comment by audn** [comment]
I just saved my profile while having my display name blank, and it seemed to have worked for me.

Can you confirm that this is still an issue?

**Comment by GamerCreator1** [comment]
No longer a issue, it looked like it solved. I will close this.
