### ISSUE TITLE
[ui] Add Bot - Developers list squashed

### ISSUE THREAD

**Issue by DanPlayz0** [discordlist-gg/beta-issues#282]
### Page

https://discordlist.gg/bot/new

### Description

The developers list has the owner, user tag squashed compared to the co-owners
![image](https://user-images.githubusercontent.com/12685647/171777333-7e684eca-8483-41f4-9d95-30292acdaa3b.png)
![image](https://user-images.githubusercontent.com/12685647/171777488-0f33dd1d-6575-4638-bdb2-839c3428ac9f.png)

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [ ] Yes

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
