### ISSUE TITLE
[bug] Private bot packs throw Internal Server Error

### ISSUE THREAD

**Issue by SorinCR** [discordlist-gg/beta-issues#288]
### Page

https://discordlist.gg/pack/4078602353066271835 and https://discordlist.gg/pack/8732709737070428189

### Description

Visiting any private packs throw Internal Server Error
New created bot packs don't do that so ig it isn't a big issue.(example: https://discordlist.gg/pack/6800410659245863725)

### Notify on issue updates

- [X] Yes

### Discord username

SorinCR#0048

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
