### ISSUE TITLE
wrong add discord server redirection on small devices

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#29]
## Description

When using the `Add Discord server` button in the menu of small devices, it redirects to `/bot/new` instead of `/server/new`.

## Possible Solution

Correct redirect.

## Steps to Reproduce (for bugs)

1. Device with small width
2. Click on the 3 lines in the top right (I think that's called a burger?) to open the menu
3. Click on `Add Discord server`
![image](https://user-images.githubusercontent.com/40232557/131232245-d021a2d2-a7d2-4c33-bb36-2198e4dcc8d3.png)

**Comment by audn** [comment]
Fixed 🎉
