### ISSUE TITLE
Searching for bots replaces title/slug but not avatar

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#291]
### Description

https://files.circuitsacul.dev/Screen_Recording_2022-06-07_at_12.54.36_PM.mov

### What browsers are you seeing the problem on?

Safari

### Notify on issue updates

- [X] Yes

### Discord username

CircuitSacul#3397

**Comment by AshMW2724** [comment]
Can replicate

https://user-images.githubusercontent.com/54909032/172616431-88309937-08c5-4430-b4cf-d0e1b8cb4a6c.mov

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
