### ISSUE TITLE
[bug] You can add yourself as Co Owner

### ISSUE THREAD

**Issue by Legit4K** [discordlist-gg/beta-issues#292]
### Description

![Screenshot_20220607_165406](https://user-images.githubusercontent.com/44619264/172485813-badb86c2-1bdf-4f66-bcb6-c8d74f15ea98.jpg)

There should be some validation to prevent adding yourself as a Co Owner. I heard there already is on both the front and back end so I'm not sure why the request still goes through. 

### Notify on issue updates

- [ ] Yes

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
