### ISSUE TITLE
[ui] Bot pack descriptions wrap in the middle of words

### ISSUE THREAD

**Issue by doinkythederp** [discordlist-gg/beta-issues#295]
### Page

https://discordlist.gg/pack/:id

### Description

When bot packs have very long descriptions, words are wrapped onto to next line. However, this breaks up words, making them harder to read and stylistically unpleasant.

![Bot pack description with several words abruptly broken](https://user-images.githubusercontent.com/75394401/172767854-90d893d1-8ee0-4b6e-bf46-744bd2c7f9d8.png)

### Preferred solution

The best way to fix this would be to not break words unless needed, and insert hyphens when breaking:

![Bot pack description featuring hyphenated breaking and words wrapped without being broken](https://user-images.githubusercontent.com/75394401/172767314-8a1c6159-6fc9-433c-ba74-6ca7c18820d4.png)

Here's what I changed to make this mockup:

```diff
- <h2 class="mt-3 text-base break-all whitespace-pre-line text-on-hero-800">
+ <h2 class="mt-3 text-base break-words whitespace-pre-line text-on-hero-800 hyphens-auto">
```

Tailwind doesn't have a `hyphens-auto` utility class by default, but you could try out [this package](https://www.npmjs.com/package/tailwindcss-hyphens) or add the following CSS:
```css
.hyphens-auto {
    -ms-hyphens: auto;
    -moz-hyphens: auto;
    -webkit-hyphens: auto;
    hyphens: auto;
}
```

### What browsers are you seeing the problem on?

Chrome

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by audn** [comment]
Hi,
Thank you for the well-written issue! 

Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
