### ISSUE TITLE
[bug] Adding Private Bots

### ISSUE THREAD

**Issue by jeweetzelfWasTaken** [discordlist-gg/beta-issues#297]
### Page

https://discordlist.gg/bot/new

### Description

When I enter a bot Id that's a private instance, it does not give me an error. I think this would be logical as people cannot invite the bot when they try to.

Yeah there's not really much to explain here, it just lets you add private bots to the site.

(btw I was allowed to enter an issue of the main website here by a mod)

### Notify on issue updates

- [X] Yes

### Discord username

jeweetzelf#5684

**Comment by ChillFish8** [comment]
We can't actually prevent this, unfortunately, Discord doesn't provide us with the information of whether it's public or private.

**Comment by audn** [comment]
Hi,
> We can't actually prevent this, unfortunately, Discord doesn't provide us with the information of whether it's public or private.

I will proceed to close the issue.

_Thank you for contributing during beta!_
