### ISSUE TITLE
[ui] The title of bot packs can be mixed up with the category

### ISSUE THREAD

**Issue by doinkythederp** [discordlist-gg/beta-issues#300]
### Page

https://discordlist.gg/packs

### Description

Right now the category is the biggest part of the bot pack.

![Screen Shot 2022-07-11 at 7 29 50 PM](https://user-images.githubusercontent.com/75394401/178395565-2866bbeb-c957-437a-b238-a6e19fc19865.png)

In my opinion, this makes it easy to confuse the category for the title of the bot pack. I think it would increase readability if the category was moved off to the side, where it is still easy to see, but not the primary component of the bot pack card.

Mockup:

![Screen Shot 2022-07-11 at 7 43 20 PM](https://user-images.githubusercontent.com/75394401/178397118-7fc5de2d-c06e-4a96-9777-efb7c32507d2.png)

### What browsers are you seeing the problem on?

Safari

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Comment by doinkythederp** [comment]
> Fixed 🎉 
> 
> 
> 
> I will proceed to close the issue.
> 
> 
> 
> _Thank you for contributing during beta!_

@audn I'm not seeing any changes. Is this in prod yet?
