### ISSUE TITLE
[bug] Commands not showing up

### ISSUE THREAD

**Issue by Luna-devv** [discordlist-gg/beta-issues#302]
### Page

https://beta.discordlist.gg/bot/857230367350063104/commands

### Description

![image](https://user-images.githubusercontent.com/71079641/182248350-b516271e-0d64-4e8c-902f-f4a932c4558b.png)
![image](https://user-images.githubusercontent.com/71079641/182248377-62a6912c-9ee2-4961-a610-525560ee8a1c.png)

### Notify on issue updates

- [X] Yes

### Discord username

ルナ#8888

**Comment by audn** [comment]
Hi,
Is this still an issue?

**Comment by Luna-devv** [comment]
Nope
