### ISSUE TITLE
[bug] Importing Commands JSON fails

### ISSUE THREAD

**Issue by Luna-devv** [discordlist-gg/beta-issues#305]
### Page

https://beta.discordlist.gg/bot/857230367350063104/commands

## Importing Array
I tried importing 18 commands using the discord JSON structure I copied from `discord.com/api/applications/:id/commands` ([Link to JSON](https://canary.discord.com/channels/724571620676599838/982572773085958175/1008732541332762764)). While doing that, I got a success message that 18 commands were added, but at the same time I landed on the `something went wrong` page. From 18 total commands, only 10 really showed up in [`/manage/commands`](https://beta.discordlist.gg/bot/857230367350063104/commands).

![https://c.lunish.nl/HELm.png](https://c.lunish.nl/r/HELm.png)
Console: [https://c.lunish.nl/7FaV.png](https://c.lunish.nl/7FaV.png)

## Importing Object
While trying to add the missing commands via JSON, I got this error
 ![https://c.lunish.nl/2bdC.png](https://c.lunish.nl/r/2bdC.png)
 
 *note that this has the same content as the conversation in [#discussions](https://canary.discord.com/channels/724571620676599838/982572773085958175/1008731811087650918)*

### Notify on issue updates

- [X] Yes

### Discord username

ルナ#8888

**Comment by Le0Developer** [comment]
There are 2 issues here:
1. the backend is limiting the length of the syntax field to 64
2. the frontend does not handle backend errors (backend gives the frontend a 400 and it just dies)

**Comment by Luna-devv** [comment]
Another thing is, how is the frontend supposed to display like 15 options some of my commands have

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
