### ISSUE TITLE
[feature] - support "loading" attribute for image tags

### ISSUE THREAD

**Issue by Wilbert-mad** [discordlist-gg/beta-issues#306]
### Description

```html
<img src="..." loading="eager" />
<img src="..." loading="lazy" />
```

lazy loading: *reduces* the initial load time of a bot page with a lot of images or high-quality image(s).
eager loading: is the default loading behavior for an image and it will request to load the image instantly.

You should consider making lazy loading the default `img` "loading" behavior on the site. - side recommendation if you end up doing this, when an image is loading set a predefined width and height so the client knows there's an image or something there to be loaded/loading.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading

### Notify on issue updates

- [x] Yes

### Discord username

Iesha#2393

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
