### ISSUE TITLE
[ui] Command names centered

### ISSUE THREAD

**Issue by shi-gg** [discordlist-gg/beta-issues#312]
### Page

https://discordlist.gg/bot/857230367350063104/commands

### Description

![image](https://user-images.githubusercontent.com/71079641/198887689-577af238-e40e-4aa2-802f-49fce910648c.png)

The command names on top are centered (which, well, looks ugly as hell).

### What browsers are you seeing the problem on?

Firefox

### Notify on issue updates

- [X] Yes

### Discord username

Luny#8888

**Comment by shi-gg** [comment]
Seems like to only occur on Firefox (106.0.2, 64-bit)
> Firefox is on top, Chrome is on the bottom
![image](https://user-images.githubusercontent.com/71079641/198887929-993a00cc-1eb4-4c85-ba2c-d29231fd7722.png)

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
