### ISSUE TITLE
[bug] - Redirect bug after logging in

### ISSUE THREAD

**Issue by A7U** [discordlist-gg/beta-issues#313]
### Page

https://discordlist.gg/[any]

### Description

**How to reproduce:**
1. Browse any page while logged out
2. Login using Discord while browsing the current page

**Expected result:**
If you're on discordlist.gg/bots for example, and you login, it should redirect to discordlist.gg/bots

**Bug:**
If you're on any page, discordlist.gg/bots for example, and you login, it redirects to discordlist.gg/botsundefined
So after logging in, it's redirecting to discordlist.gg/[slug]undefined

I'm not quite sure what parameter it's trying to pass in the redirect URL, but it seems to be undefined. 
The bug happens on all pages. I will attach some gifs here:

![chrome_SDY8YX12Tw](https://user-images.githubusercontent.com/57374241/200860445-653b18cf-dd3c-4cf9-9d94-e7870df249ac.gif)
![chrome_W4cTyFbBUN](https://user-images.githubusercontent.com/57374241/200860463-323a4a29-72c5-46a3-b208-f6caf2371c8a.gif)

### Notify on issue updates

- [X] Yes

### Discord username

A7U#1001

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
