### ISSUE TITLE
[bug] api error when signing in

### ISSUE THREAD

**Issue by SHACKASTJ** [discordlist-gg/beta-issues#314]
### Page

https://discordlist.gg/bot/429457053791158281/vote

### Description

Al querer hacer valido el voto de discordlist.gg el bot se queda en cargando. Si  hago click aparece este mensaje.

**Translated**
When trying to validate the discordlist.gg vote, the bot stays loading. If I click this message appears.
![Screenshot_20221110-041940_Chrome](https://user-images.githubusercontent.com/83619220/201090534-b50b1ca9-cd73-4a7c-ad42-c6ea55204d1c.jpg)

![Screenshot_20221110-042342_Chrome](https://user-images.githubusercontent.com/83619220/201090927-fd6f6432-3f74-42f0-9bd0-8847e96704d5.jpg)

### Notify on issue updates

- [X] Yes

### Discord username

sHaCkAzTJ#3499

**Comment by audn** [comment]
Hi,
This is an issue that we're trying to fix. We have no ETA. atm unfortunately 

Hola,
Actualmente, este es un problema que estamos tratando de solucionar. No tenemos ETA. lamentablemente cajero automático

_Thank you for contributing during beta!_
