### ISSUE TITLE
[bug] Bot cards on homepage take up too much space

### ISSUE THREAD

**Issue by lewisfm** [discordlist-gg/beta-issues#315]
### Page

https://discordlist.gg

### Description

The "Trending bots" cards are very wide and overlapping with each other.

![image](https://user-images.githubusercontent.com/75394401/201450212-fa777aef-c940-4c58-99a3-fca0219e6538.png)

This appears to be caused by the `min-w-full` class. I removed it from the first 3 and they looked fine.

![image](https://user-images.githubusercontent.com/75394401/201450227-b61f9ccf-9d9b-4a0d-8534-24c46904d8f4.png)

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by lewisfm** [comment]
The "View" button isn't usable until this is fixed.

**Comment by audn** [comment]
Hi,
What browser is this?

**Comment by lewisfm** [comment]
Safari 16.1

**Comment by audn** [comment]
Followed up in Discord (channel ID: 1040798831702454293)

**Comment by lewisfm** [comment]
@audn Looks fixed to me!
![Screenshot 2022-11-13 at 11 37 58 AM](https://user-images.githubusercontent.com/75394401/201540823-d6e23593-7dff-43e6-9090-93ba771373fc.png)
