### ISSUE TITLE
[bug] Two redirects when clicking on categories

### ISSUE THREAD

**Issue by shi-gg** [discordlist-gg/beta-issues#316]
### Page

https://discordlist.gg

### Description

If you go to a bot here, it goes to the bot and direct after to the tag aka redirects twice
![image](https://user-images.githubusercontent.com/71079641/201982179-fda0aa20-8d38-459e-9920-26b84fd67ba2.png)

<https://discordlist.gg/> => 
<https://discordlist.gg/bot/857230367350063104> => 
<https://discordlist.gg/bots/economy>

### Notify on issue updates

- [X] Yes

### Discord username

Luny#8888

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
