### ISSUE TITLE
[feature] "All Commands" tab

### ISSUE THREAD

**Issue by shi-gg** [discordlist-gg/beta-issues#319]
### Description

A tab where you can see all commands just in such a list (of course without being able to change the tab of each row, just like that because I used paint to show)
![image](https://user-images.githubusercontent.com/71079641/214821913-c89e0726-f34b-4f8c-896c-b7bbe5c52c8b.png)

### Notify on issue updates

- [X] Yes

### Discord username

audn#1580

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
