### ISSUE TITLE
[Bug] Support Server Invite validity checker is broken

### ISSUE THREAD

**Issue by PikaDude** [discordlist-gg/beta-issues#32]
## Description
The support server invite option on the bot form will always return "Not a valid server link!" regardless if it is actually valid.

## Steps to Reproduce (for bugs)
![image](https://user-images.githubusercontent.com/18642415/131254626-3111511e-3e10-4370-97c3-b9ee6ad81e60.png)

**Comment by audn** [comment]
Fixed 🎉
