### ISSUE TITLE
[feature] One-time report feature for bots

### ISSUE THREAD

**Issue by Wydady13** [discordlist-gg/beta-issues#321]
### Description

 Add a feature that allows users to report a bot only once.

### Notify on issue updates

- [X] Yes

### Discord username

Wydady#2444

**Comment by audn** [comment]
Why only once?

**Comment by Wydady13** [comment]
I mean, for example, when you file a report, write the reason, submit, go to a second bot, and want to file a new report, the same reason you wrote appears.

**Comment by audn** [comment]
Hi,
We've concluded that it isn't necessary at this time.

If desired, you are more than welcome to reopen the case *(preferably with a counter-argument)* - if you don't agree with our response.

I will proceed to close the issue.
