### ISSUE TITLE
[bug] Authors' profile pictures not working

### ISSUE THREAD

**Issue by Wydady13** [discordlist-gg/beta-issues#322]
### Page

https://discordlist.gg/bot/847273457519689801

### Description

Some authors' profile pictures are not displaying properly in the bot page, even though they appear correctly when their profiles are opened

https://cdn.discordapp.com/attachments/1071193834324770857/1088157823088734218/image.png
https://cdn.discordapp.com/attachments/1071193834324770857/1088158207203102840/image.png

### Notify on issue updates

- [X] Yes

### Discord username

Wydady#2444

**Comment by audn** [comment]
Hi,
For future references, please attach images instead of adding an external link / downloadable files.
