### ISSUE TITLE
[server-error] /user/804265795835265034

### ISSUE THREAD

**Issue by ThatBadName** [discordlist-gg/beta-issues#326]
### Page

https://discordlist.gg/user/804265795835265034

### Description

![image](https://github.com/discordlist-gg/beta-issues/assets/90130690/84266628-c7c9-4851-b00a-750647ab81c9)

### Notify on issue updates

- [X] Yes

### Discord username

thatbadname

**Comment by audn** [comment]
I can't recreate this, is it still happening on your end?

**Comment by ThatBadName** [comment]
no its fine now
