### ISSUE TITLE
[server-error] /bot/1044791133416464384/manage/analytics

### ISSUE THREAD

**Issue by lewisfm** [discordlist-gg/beta-issues#327]
### Page

https://discordlist.gg/bot/1044791133416464384/manage/analytics

### Description

I think this has to do with authorization because after this I was logged out. Or maybe that was because I closed the browser window, I'm not sure. Anyway all the graph numbers were NaN and when I clicked on "engagement" it finally gave out and crashed.

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp

**Comment by audn** [comment]
I can't recreate this, is it still happening on your end?

**Comment by lewisfm** [comment]
Yep! https://github.com/discordlist-gg/beta-issues/assets/75394401/42306455-a064-4f15-ac47-8e594211ede9

**Comment by audn** [comment]
Are you logged in? What happens if you refresh the page?

**Comment by audn** [comment]
Hi,
Closing this issue as stale due to inactivity. 

Feel free to reopen if you're still experiencing issues.
