### ISSUE TITLE
[bug] No redirect

### ISSUE THREAD

**Issue by jonas0042** [discordlist-gg/beta-issues#328]
### Page

https://discordlist.gg/premium

### Description

1. Dont be logged in on website

Click on "pricing" and then continue using "Next". 
Redirects to https://api.discordlist.gg/v0/auth/login (JSON Response)

Better: dont allow the "next" click if not logged in / notify the user

### Notify on issue updates

- [ ] Yes

### Discord username

BlaueEnte

**Comment by audn** [comment]
This is a 'hidden' page. It's not intended to be functional, as we currently do not offer a premium service on Discordlist.
