### ISSUE TITLE
[Bug] Submit button does not disable when clicked

### ISSUE THREAD

**Issue by PikaDude** [discordlist-gg/beta-issues#33]
## Description
The submit button on the bot form does not become disabled upon clicking (nor does it have an internal disable) which allows people to spam the button which will cause the bot form to be submitted multiple times.

## Possible Solution
- Disable the button once clicked
- If the user tries to click the button after they already clicked it, don't send the submit request again

## Steps to Reproduce (for bugs)
1. Spam the submit button on the bot form

**Comment by audn** [comment]
Fixed 🎉 (will be better once frontend adds more validation)
