### ISSUE TITLE
[bug] Webhook test always returns 500

### ISSUE THREAD

**Issue by OIRNOIR** [discordlist-gg/beta-issues#331]
### Page

https://discordlist.gg/bot/807692666107985941/manage/webhooks

### Description

When sending a webhook test, it always says on the page that my server responded with a 500 error, despite the fact that my server recieved it and responded to it successfully with a 200. I can reproduce the correct behavior in my server by sending the JWT recieved prior from DList via a manual fetch request and it returns 200, so I don't know where the 500 is coming from. I don't think it's an issue on my end.

### Notify on issue updates

- [X] Yes

### Discord username

oirnoir

**Comment by audn** [comment]
@OIRNOIR did you mean to close this?

**Comment by OIRNOIR** [comment]
I closed it because I gave up. Feel free to try and reproduce it though
