### ISSUE TITLE
[server-error] /bot/new

### ISSUE THREAD

**Issue by delfinaai** [discordlist-gg/beta-issues#332]
### Page

https://discordlist.gg/bot/new

### Description

no andaa

### Notify on issue updates

- [x] Yes

### Discord username

la_latinaai#0

**Comment by audn** [comment]
Hi,
What's the issue exactly?

**Comment by delfinaai** [comment]
me tira error

**Comment by delfinaai** [comment]
no me detecta el bot

**Comment by audn** [comment]
Hi,
Closing this as it’s not reproducible.
