### ISSUE TITLE
Hrefs on embed returns to invalid link 

### ISSUE THREAD

**Issue by suffocated** [discordlist-gg/beta-issues#35]
## Description
On href links to my profile, the bot returns 338729885897981956 my id + my slug, so 338729885897981956o

## Possible Solution
Just don't use the slug in the link ez

**Comment by suffocated** [comment]
https://beta.discordlist.gg/user/338729885897981956o was the link that the bot returned when I tapped on my hyperlink

**Comment by OhB00** [comment]
Fixed in https://github.com/discordlist-gg/web-back/commit/57c6210a31aca6590bc991ed09d4f146c155902b
