### ISSUE TITLE
"Unsaved changes alert" isn't sticky further causing overlaping

### ISSUE THREAD

**Issue by suffocated** [discordlist-gg/beta-issues#36]
## Description
The unsaved changes alert isn't sticky, rendering the alert overlapping with different elements on the page.

## Possible Solution
Make it sticky 

## Steps to Reproduce (for bugs)
1. Have something unsaved
2. Observe

![image](https://user-images.githubusercontent.com/47527704/131270848-9d1cb161-68c2-4f30-a81b-ba1b5ace62fd.png)
![image](https://user-images.githubusercontent.com/47527704/131270851-b713161d-7974-426b-b27e-b2a96b003696.png)

**Comment by audn** [comment]
What do you mean isn't sticky? The wanted behavior is to follow scroll (aka sticky)
