### ISSUE TITLE
/user @SCDerox returns "This interaction failed"

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#39]
## Description
If I try to see my profile and execute the command `/user user:<@413429490342035466>` (`/user @SCDerox` in Discord) Discord returns "This interaction failed".
![screen_20210830-110533](https://user-images.githubusercontent.com/43812987/131315272-a450faeb-ebc4-4e32-9852-613eb5d0fa85.png)

## Steps to Reproduce (for bugs)
1. Open any channel on the DCList.gg-Discord in which Slash-Commands can be executed 
2. Enter `/user` and select @SCDerox 
3. Execute the command
4. Observe how it fails

Not a client-side-bug btw, this could be reproduced by other users on the discord too.

**Comment by OhB00** [comment]
This happens occasionally and I have absolutely no idea why, it usually appears to start working after some time.

Going to be forking the commands library im using and hopefully resolve this?

**Comment by OhB00** [comment]
Wow seems to be your profile in particular, very strange

**Comment by OhB00** [comment]
Happens when users have empty strings for fields as these are not optional in the discord api, error handling was not catching it

**Comment by OhB00** [comment]
Fixed in  https://github.com/discordlist-gg/web-back/commit/4cc199409fff2abf24f4ff6d68df2840cc3fa95f
