### ISSUE TITLE
Valid invite in support_server_url on create bot endpoint returns "The URL path is not valid." 

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#4]
## Expected Behavior
Bot is created with the right URL as support_server_url.

## Current Behavior
Calling `/v0/bots` with `  "support_server_url": "https://discord.com/invite/abc",` as parameter returns 400 with the following content:
```json
{
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "support_server_url": [
      "The URL path is not valid."
    ]
  }
}
``` 

## Possible Solution
Check code that validates discord server urls.

## Steps to Reproduce (for bugs)
1. Call POST on `/v0/bots` with `"support_server_url": "https://discord.com/invite/abc"` as a JSON parameter.
2. Read the returned 400 error.

## Context
I can't create a bot ):

I was told to tag @ohb00 ^^

**Comment by OhB00** [comment]
Fixed
