### ISSUE TITLE
No error message whilst saving an taken or invalid slug

### ISSUE THREAD

**Issue by suffocated** [discordlist-gg/beta-issues#41]
## Description
While going to your profile and attempting to save either an taken or invalid slug, you'll not recieve an error message

## Possible Solution
Make it so that while you get an 403 error, that it notifies the user.

## Steps to Reproduce (for bugs)
1. Head over to your profile
2. Attempt to take a taken or invalid slug
3. Observe

**Comment by audn** [comment]
Fixed 🎉
