### ISSUE TITLE
"Edit banner"-Button is visible on other's profiles

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#43]
## Description
![screen_20210831-145314](https://user-images.githubusercontent.com/43812987/131505879-4d01357b-3b91-4fa5-b429-9c29220cf5c3.png)

## Possible Solution
Don't show the button

## Steps to Reproduce (for bugs)

1. Go to https://beta.discordlist.gg/user/123057713482694658 or any other profile

**Comment by audn** [comment]
Fixed 🎉
