### ISSUE TITLE
Custom slugs without premium

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#44]
## Description
When attempting to set a custom slug (for users without premium), the server throws a 403 but the user is not notified of an error.

## Possible Solution
Grey out the premium features for users without premium.

## Steps to Reproduce (for bugs)
1. Open your profile (an account without premium).
2. Keep your browser console open.
3. Click on `Edit profile` and try to change your slug.
4. Your console shows requests failing with 403's.
5. Clicking on "save" neither saves the settings nor throws an error.

**Comment by retraigo** [comment]
Additional comment: Removing premium retains the slug.

**Comment by audn** [comment]
I'm able to set a custom slug without premium. Is this still an issue?

**Comment by retraigo** [comment]
![Screenshot from 2021-08-31 21-45-54](https://user-images.githubusercontent.com/56877379/131539066-78c52fa1-4553-44a9-8f16-1946d08c98dd.png)
It indeed is

**Comment by audn** [comment]
Fixed 🎉
