### ISSUE TITLE
Remove slug when downgrading (same for banner if that's premium only)

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#46]
## Description
After you downgrade (for example when you can't be charged, cancel, use `/beta premium`, etc)  the slug should be removed automatically.
If the banner should be premium-only, it should also get removed.

Opened as requested by [brace](https://discord.com/channels/724571620676599838/736932833863663646/882330782893498378).

**Comment by OhB00** [comment]
damn you beat me to it
