### ISSUE TITLE
[Bug] ToS notification shown at every new session

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#48]
## Description
The terms of service and privacy policy notification is shown at the start of every new session even after accepting it each time.

## Steps to Reproduce (for bugs)
1. Open the website.

![Screenshot 2021-09-01 at 15-59-14 dlist gg Discover a huge variety of bots servers ](https://user-images.githubusercontent.com/56877379/131656724-cf6cff5c-b248-4d1a-9129-e8cecddb9e0b.png)

**Comment by audn** [comment]
I've noticed it as well, but I'm not sure why it's happening.
Next time, can you check cookies for either `dlist.cookies` or `acceptedCookies`? If they exist, what's their value?

**Comment by retraigo** [comment]
`dlist.cookies` does not exist at the start of the session. When I click on **Accept**, `dlist.cookies` is set to `"true"` with expires/maxAge set to `Session`.
