### ISSUE TITLE
[Bug] Editing long description resets short description

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#49]
## Description
Editing long description of a bot while creating a new bot resets the brief description. 

## Steps to Reproduce (for bugs)
1. Open the new bot creation form
2. Type something in the brief description
3. Now edit the long description
4. Brief description gets reset
5. 
![Screenshot 2021-09-01 at 16-26-04 Adding bot dlist gg](https://user-images.githubusercontent.com/56877379/131659840-2d894ff0-ad0a-411e-bb48-6ea19efbb6e7.png)

![Screenshot 2021-09-01 at 16-26-16 Adding bot dlist gg](https://user-images.githubusercontent.com/56877379/131659835-b35cc915-30fb-424d-b0e8-4e915d1115a4.png)

**Comment by retraigo** [comment]
Don't mind the grammarly icon

**Comment by OhB00** [comment]
(fix will not be published until audun makes a commit cuz vercel :))
