### ISSUE TITLE
[Suggestion] Make bot application fields mandatory

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#50]
## Description
When adding a new bot, a number of fields such as "Tags" are not mandatory. Even agreeing to the guidelines is not mandatory. Making these fields mandatory would prevent bugs (such as showing "Error" when a prefix is not provided).

**Comment by OhB00** [comment]
This is not a bug, prefix is not required because slash commands are a thing. If you don't feel your bot is within any tag, you don't need to tag your bot, we would rather have accurately tagged bots. Making fields mandatory is not a good way to fix bugs.

**Comment by retraigo** [comment]
Yea that indeed makes sense. However, there's also the checkbox for agreeing to the guidelines and it is not a required field.
