### ISSUE TITLE
[Bug] Editing bot details

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#51]
## Description
This one just happens to be a really big bug.

1. Attempting to edit a newly created bot shows a form with all existing bot details as intended.
2. Editing the bot does not show any results except for the console being spammed with `saved` despite not having saved. 
3. Closing the page and coming back to edit the bot shows a completely empty form with all bot details missing.

## Steps to Reproduce (for bugs)
Refer description

**Comment by audn** [comment]
Page isn't done
