### ISSUE TITLE
[Typo] Adding bots to bot packs

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#54]
## Original text
We're only you packs where dlist.gg doesn't already exist.

## New text
I have no idea what that's supposed to mean... Maybe...

**We're only `showing` you packs where dlist.gg doesn't already exist.**

## Link to the page this typo was found on
From adding a bot to a bot pack
![Screenshot 2021-09-06 at 15-34-06 dlist gg dlist gg](https://user-images.githubusercontent.com/56877379/132200822-fa0ee429-54ae-4382-9d5c-60f905ab9ac4.png)

**Comment by audn** [comment]
How is this?
![image](https://user-images.githubusercontent.com/21041399/132285279-dcb69848-6bdb-4a21-9db9-9acc6b95720f.png)

**Comment by retraigo** [comment]
Quite good

**Comment by audn** [comment]
Thank you!
