### ISSUE TITLE
[Bug] Only the latest bot pack not shown in list

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#55]
## Description
I add a bot to a couple of bot packs and click on `Add to bot pack` again.

### Expected Behavior
Both bot packs that include the bot don't get displayed in the modal (from roughly trying to make out #54)

### Current Behavior
Only one bot pack doesn't get displayed.

## Possible Solution
From what I saw in the console, `user.packs` is an array with four items. `Primordial Evil` (refer steps to reproduce for context) is the first item in the array and it gets tested and skipped. The other three bot packs appear normally. Maybe something only the first item in `user.packs` is checked?

## Steps to Reproduce (for bugs)
1. I made a bot pack named conqueror of evil
2. It didn't show up (I dont have a screenshot sry)
3. I made another bot pack with the same name
4. This is the bot pack list now
![Screenshot 2021-09-06 at 15-34-06 dlist gg dlist gg](https://user-images.githubusercontent.com/56877379/132201931-b893e09f-532b-451e-9c53-4760b5bb2c36.png)
5. I made another bot pack named Primordial Evil
6. Now this is the bot pack list
![Screenshot 2021-09-06 at 15-44-03 dlist gg dlist gg](https://user-images.githubusercontent.com/56877379/132202073-581c5210-2247-43bd-8339-bb03b2d3788c.png)
7. So I made another bot pack named Master of Evil
8. Now this is the list 
![Screenshot 2021-09-06 at 15-49-38 dlist gg dlist gg](https://user-images.githubusercontent.com/56877379/132202381-5479d433-4573-4e59-b227-c9e61a39e6cd.png)
9. Suppose I test it with any other bot, all four packs are displayed.
![Screenshot 2021-09-06 at 16-03-06 Dank Memer dlist gg](https://user-images.githubusercontent.com/56877379/132204676-1f4154a4-5211-4582-a545-b1a8cdaae5da.png)

PS: All four bot packs have dlist.gg as the only bot.

**Comment by audn** [comment]
As the first image says: 
![image](https://user-images.githubusercontent.com/21041399/132283915-d309e1e8-c732-4cc9-99a0-8124784f1202.png)


We're only going to show you packs that you can actually add the bot to, and we do not allow adding the same bot twice. That's probably why it didn't show up.

Now that you know this behavior, can you try again?

**Comment by retraigo** [comment]
As I said, all the bot packs only had dlist.gg as the bot. So none of them should have shown up right?

**Comment by audn** [comment]
There is a bug where you can actually see the packs even when the alert is there 😳 That's why it didn't show up the first time (aka it worked) - but when you make a new one, the system doesn't notice it.

I'll see if I can get a fix out for it today!

**Comment by retraigo** [comment]
Well the bug I reported is different. The system only checks whether the bot exists in the first bot pack and omits it. As you see, only one bot pack is missing among them. 

Like if we have bot packs a, b, c, d and e, and all packs include the bot in question, only `a` is omitted while `b` to `e` are shown even if they include the bot.

This has been verified with multiple attempts, refreshing the page each time.

**Comment by audn** [comment]
Oh shit, yea you are right!

I stumbled across this issue an hour ago, but I fixed it on my local version. I'll push it out and notify you when it's rolled out 🍕

**Comment by audn** [comment]
I think this is fixed! 
reopen issue if not
