### ISSUE TITLE
[Bug] Display Name field cuts off input

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#56]
## Description
When entering text in the `Display Name` field in the `Edit Profile` modal, text longer than the length of the field gets cut off. However, the `Slug` field next to it does not cut off text like that. For example, my name is supposed to be `Tenebrae Von Dunkelheit` but it gets cut off at `Dunkelhe`. 

The input still works and it is a visual bug. My name after saving successfully gets changed to `Tenebrae Von Dunkelheit`.

![Screenshot 2021-09-06 at 18-13-01 NeTT dlist gg](https://user-images.githubusercontent.com/56877379/132220156-ad2b992c-adaf-47a2-9857-fcdef515ab14.png)

## Steps to Reproduce (for bugs)
1. Navigate to your profile.
2. Edit profile.
3. Type a long-ass name in the `Display Name` field.

Edit: Added image

**Comment by audn** [comment]
It's not being cut off, you just need to scroll sideways
![image](https://user-images.githubusercontent.com/21041399/132283747-a3b8010a-7e5b-4c19-a4a1-97510f2514bf.png)
![image](https://user-images.githubusercontent.com/21041399/132283754-064d0618-0566-47c6-a2cc-22fbd7ebc163.png)

**Comment by retraigo** [comment]
Maybe it's a bug on my browser then. I can scroll sideways on the "slug" field but not on the "display name" field

**Comment by audn** [comment]
Can you try placing your cursor on the last letter and click the right arrow on your keyboard?

**Comment by retraigo** [comment]
Wifi's down rn and I can't access the site on my phone for some reason. I'll check that when wifi's back

**Comment by audn** [comment]
What phone do you have?

**Comment by retraigo** [comment]
Ah its a OnePlus. I'm just getting a 401 when I try to check the site.
![Screenshot_20210908-131614.jpg](https://user-images.githubusercontent.com/56877379/132468392-bd824d44-5820-4120-9512-fff554885fda.jpg)

**Comment by audn** [comment]
Try clearing your cookies
