### ISSUE TITLE
[Bug] Messed up modal title in Firefox

### ISSUE THREAD

**Issue by retraigo** [discordlist-gg/beta-issues#62]
## Description
The modal headers (and probably footers too) are messed up when using Firefox. The parent flexbox does not take up the entire width. This cannot be reproduced on chromium browsers.

![Screenshot from 2021-09-25 16-31-30](https://user-images.githubusercontent.com/56877379/134769370-d971c666-7606-49ae-b899-9d23a42866a5.png)

![Screenshot from 2021-09-25 16-38-24](https://user-images.githubusercontent.com/56877379/134769371-9e7ddcfc-b86b-484b-9af6-06926e7fbc90.png)

## Possible Solution
The issue could be due to firefox not supporting `-webkit-fill-available`.

Replace `w-[-webkit-fill-available]` in `modalTitle` and `modalFooter` with something like `w-full`.

**Comment by audn** [comment]
Fixed 🎉
