### ISSUE TITLE
api methods

### ISSUE THREAD

**Issue by Le0Developer** [discordlist-gg/beta-issues#7]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior
HTTP Methods that make sense for the api endpoint.

## Current Behavior
They don't make sense

## Possible Solution

|  API Endpoint           |  Current Method  |  Better Method  |
|-------------------------|------------------|-----------------|
|  /v0/bots/{id}/reports  |  PUT             |  POST           |
|  /v0/bots/{id}          |  POST            |  PATCH          |
|  /v0/users/me           |  POST            |  PATCH          |
|  /v0/users/me/slug      |  POST            |  PATCH          |
|  /v0/users/me/banner    |  POST            |  PATCH          |
|  /v0/packs/{id}         |  POST            |  PATCH          |
|  /v0/packs/{id}/settings         |  POST            |  PATCH          |
|  /v0/payments/token     |  POST            |  PATCH          |

cc: @ohb00

**Comment by OhB00** [comment]
Internal API methods. Keeping them how they are for the moment, might change in the future.
