### ISSUE TITLE
Add a new bot lead to 404 on save

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#90]
## Description
![image](https://user-images.githubusercontent.com/58714825/137366107-6a4d6f75-75bf-4074-a93e-7dac1ccf1b11.png)

**Comment by OhB00** [comment]
Super weird issue, should be fixed https://github.com/discordlist-gg/web-back/commit/1d950f7416ff3a4d579c0bf0cccc3c826f1cf23c
