### ISSUE TITLE
[bug] need more data on /bot/id

### ISSUE THREAD

**Issue by audn** [discordlist-gg/beta-issues#96]
Need to know if bot is hidden, forced into hiding, and if people can add it to packs

```{
  is_hidden:" string";
  is_forced_into_hiding: " string";
  is_packable: " string";
```

**Comment by OhB00** [comment]
These are bools, but yep can do

**Comment by audn** [comment]
oh shit my bad lmao, thanks bryceinator <3 perfect timing
streaming atm

**Comment by OhB00** [comment]
Fixed https://github.com/discordlist-gg/web-back/commit/0fd41775c72f5e7c3339222afe12016e54820e48
